Repository XRPLF/rippled, pull requests merged in 2022-12, with the labels that each got.

#4357 Update Github Actions to ubuntu-latest:
  .github/workflows/clang-format.yml
  .github/workflows/doxygen.yml
  .github/workflows/levelization.yml
Labels: Passed, CI, Dependencies

#4332 Work around gdb bug by changing a template parameter:
  src/ripple/protocol/SField.h
  src/ripple/protocol/STBitString.h
Labels: Passed

#4325 Fix clang 15 warnings
  src/ripple/app/misc/impl/TxQ.cpp
  src/ripple/core/impl/Config.cpp
  src/ripple/rpc/impl/Status.cpp
  src/test/unit_test/multi_runner.cpp
Labels: Passed, Testable

#4323 Catch transaction deserialization error in doLedgerGrpc
  src/ripple/rpc/handlers/LedgerHandler.cpp
Labels: Passed, Bug, Testable

#4367 Use the Conan package manager
  .github/workflows/nix.yml
  .github/workflows/windows.yml
  .gitlab-ci.yml
  .travis.yml
  BUILD.md
  Builds/CMake/FindRocksDB.cmake
  Builds/CMake/README.md
  Builds/CMake/RippledCore.cmake
  Builds/CMake/RippledDocs.cmake
  Builds/CMake/RippledInstall.cmake
  Builds/CMake/RippledInterface.cmake
  Builds/CMake/RippledMultiConfig.cmake
  Builds/CMake/RippledNIH.cmake
  Builds/CMake/RippledRelease.cmake
  Builds/CMake/RippledSanity.cmake
  Builds/CMake/deps/Boost.cmake
  Builds/CMake/deps/Ed25519-donna.cmake
  Builds/CMake/deps/FindBoost.cmake
  Builds/CMake/deps/Findjemalloc.cmake
  Builds/CMake/deps/Findlibarchive_pc.cmake
  Builds/CMake/deps/Findlz4.cmake
  Builds/CMake/deps/Findsecp256k1.cmake
  Builds/CMake/deps/Findsnappy.cmake
  Builds/CMake/deps/Findsoci.cmake
  Builds/CMake/deps/Findsqlite.cmake
  Builds/CMake/deps/Libarchive.cmake
  Builds/CMake/deps/Lz4.cmake
  Builds/CMake/deps/Nudb.cmake
  Builds/CMake/deps/OpenSSL.cmake
  Builds/CMake/deps/Postgres.cmake
  Builds/CMake/deps/Protobuf.cmake
  Builds/CMake/deps/Rocksdb.cmake
  Builds/CMake/deps/Secp256k1.cmake
  Builds/CMake/deps/Snappy.cmake
  Builds/CMake/deps/Soci.cmake
  Builds/CMake/deps/Sqlite.cmake
  Builds/CMake/deps/cassandra.cmake
  Builds/CMake/deps/date.cmake
  Builds/CMake/deps/gRPC.cmake
  Builds/CMake/rocks_thirdparty.inc
  Builds/CMake/rocksdb_build_version.cc.in
  Builds/CMake/soci_patch.cmake
  CMakeLists.txt
  conanfile.py
  external/rocksdb/conanfile.py
  external/rocksdb/thirdparty.inc
  src/ed25519-donna/CMakeLists.txt
  src/ripple/protocol/impl/PublicKey.cpp
  src/ripple/protocol/impl/SecretKey.cpp
  src/ripple/rpc/handlers/WalletPropose.cpp
  src/secp256k1/CMakeLists.txt
  src/test/core/SociDB_test.cpp
Labels: Build System, Dependencies, High Priority, Will Need Documentation
