Repository XRPLF/rippled, pull requests merged in 2022-11, with the labels that each got.

#4018 [TRIVIAL] Update Linux Build Instructions
  Builds/linux/README.md
Labels: Rebase

#4351 Don't try to read SLE with key 0 from the ledger:
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
  src/test/app/NFToken_test.cpp
Labels: Passed, Bug

#3890 README - add link to ripple-server mailing list
  README.md
Labels: Passed
