Repository XRPLF/rippled, pull requests merged in 2023-01, with the labels that each got.

#4143 RPC tooBusy response now has 503 HTTP status code:
  src/ripple/net/impl/RPCCall.cpp
  src/ripple/protocol/ErrorCodes.h
  src/ripple/protocol/impl/ErrorCodes.cpp
  src/ripple/rpc/impl/ServerHandlerImp.cpp
  src/ripple/server/impl/JSONRPCUtil.cpp
  src/test/rpc/LedgerRPC_test.cpp
Labels: Passed, API Change, Testable, Will Need Documentation

#4287 Add a unit test for invalid memos
  Builds/CMake/RippledCore.cmake
  src/test/protocol/Memo_test.cpp
Labels: Needs Review, Trivial

#4379 Make NodeToShardRPC a manual test
  src/test/rpc/NodeToShardRPC_test.cpp
Labels: CI

#4383 Try to help readers of BUILD.md
  BUILD.md
Labels: Documentation, Trivial

#4391 Add fixUnburnableNFToken feature
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
Labels: Passed
