Repository XRPLF/rippled, pull requests merged in 2023-09, with the labels that each got.

#4674 AMMBid: use tecINTERNAL for 'impossible' errors
  src/ripple/app/tx/impl/AMMBid.cpp
Labels: Amendment, Clio Reviewed, XLS-30

#4312 Introduce replacement for getting and setting thread name:
  Builds/CMake/RippledCore.cmake
  src/ripple/app/ledger/impl/LedgerCleaner.cpp
  src/ripple/app/main/BasicApp.cpp
  src/ripple/app/main/GRPCServer.cpp
  src/ripple/app/main/LoadManager.cpp
  src/ripple/app/main/Main.cpp
  src/ripple/app/misc/SHAMapStoreImp.cpp
  src/ripple/app/reporting/ETLSource.cpp
  src/ripple/app/reporting/ReportingETL.cpp
  src/ripple/basics/ThreadUtilities.h
  src/ripple/basics/impl/ThreadUtilities.cpp
  src/ripple/beast/core/CurrentThreadName.cpp
  src/ripple/core/impl/Job.cpp
  src/ripple/core/impl/SNTPClock.cpp
  src/ripple/core/impl/Workers.cpp
  src/ripple/nodestore/backend/RocksDBFactory.cpp
  src/ripple/nodestore/impl/Database.cpp
  src/ripple/perflog/impl/PerfLogImp.cpp
  src/ripple/resource/impl/ResourceManager.cpp
  src/test/basics/ThreadName_test.cpp
  src/test/overlay/short_read_test.cpp
Labels: Passed, Tech Debt

#4667 [TRIVIAL] Update rippled-example.cfg docs to clarify usage of ssl_cert vs ssl_chain
  cfg/rippled-example.cfg
Labels: Documentation

#4630 APIv2(ledger_entry) : check error
  src/ripple/protocol/impl/Issue.cpp
  src/ripple/rpc/handlers/LedgerEntry.cpp
  src/test/rpc/LedgerRPC_test.cpp
Labels: API Change, Testable, Will Need Documentation, Clio Reviewed

#4637 refactor: simplify `TxFormats` common fields logic
  src/ripple/protocol/impl/TxFormats.cpp
Labels: Tech Debt

#4338 Update SECURITY.md
  SECURITY.md
Labels: Documentation, Trivial

#4697 Remove CurrentThreadName.h from RippledCore.cmake
  Builds/CMake/RippledCore.cmake
Labels: Passed

#4503 Asynchronously write batches to NuDB.
  src/ripple/nodestore/Types.h
  src/ripple/nodestore/backend/NuDBFactory.cpp
Labels: Passed, Performance/Resource Improvement

#4505 Several changes to improve Consensus stability:
  Builds/levelization/results/ordering.txt
  src/ripple/app/consensus/RCLConsensus.cpp
  src/ripple/app/consensus/RCLConsensus.h
  src/ripple/app/consensus/RCLCxPeerPos.h
  src/ripple/app/ledger/LedgerMaster.h
  src/ripple/app/ledger/impl/LedgerMaster.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/impl/ValidatorList.cpp
  src/ripple/beast/container/detail/aged_unordered_container.h
  src/ripple/consensus/Consensus.cpp
  src/ripple/consensus/Consensus.h
  src/ripple/consensus/ConsensusParms.h
  src/ripple/consensus/ConsensusProposal.h
  src/ripple/consensus/ConsensusTypes.h
  src/ripple/consensus/DisputedTx.h
  src/ripple/overlay/impl/PeerImp.cpp
  src/ripple/proto/ripple.proto
  src/test/consensus/Consensus_test.cpp
  src/test/csf/Peer.h
  src/test/csf/Proposal.h
Labels: Passed, Performance/Resource Improvement

#4620 APIv2(account_tx, noripple_check): return error for invalid input (fix #4543)
  src/ripple/rpc/handlers/AccountInfo.cpp
  src/ripple/rpc/handlers/AccountTx.cpp
  src/ripple/rpc/handlers/NoRippleCheck.cpp
  src/test/rpc/AccountTx_test.cpp
  src/test/rpc/NoRipple_test.cpp
Labels: API Change, Clio Reviewed

#4292 XLS-38d: XChainBridge (side chains)
  Builds/CMake/CMakeFuncs.cmake
  Builds/CMake/RippledCore.cmake
  Builds/CMake/RippledRelease.cmake
  CMakeLists.txt
  src/ripple/app/main/Application.cpp
  src/ripple/app/main/Main.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/tx/impl/InvariantCheck.cpp
  src/ripple/app/tx/impl/InvariantCheck.h
  src/ripple/app/tx/impl/XChainBridge.cpp
  src/ripple/app/tx/impl/XChainBridge.h
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/beast/utility/Journal.h
  src/ripple/core/Config.h
  src/ripple/overlay/PeerReservationTable.h
  src/ripple/protocol/AccountID.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/Indexes.h
  src/ripple/protocol/LedgerFormats.h
  src/ripple/protocol/PublicKey.h
  src/ripple/protocol/SField.h
  src/ripple/protocol/STAccount.h
  src/ripple/protocol/STAmount.h
  src/ripple/protocol/STArray.h
  src/ripple/protocol/STIssue.h
  src/ripple/protocol/STXChainBridge.h
  src/ripple/protocol/TER.h
  src/ripple/protocol/TxFlags.h
  src/ripple/protocol/TxFormats.h
  src/ripple/protocol/XChainAttestations.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/Indexes.cpp
  src/ripple/protocol/impl/InnerObjectFormats.cpp
  src/ripple/protocol/impl/Issue.cpp
  src/ripple/protocol/impl/LedgerFormats.cpp
  src/ripple/protocol/impl/SField.cpp
  src/ripple/protocol/impl/STAmount.cpp
  src/ripple/protocol/impl/STArray.cpp
  src/ripple/protocol/impl/STIssue.cpp
  src/ripple/protocol/impl/STParsedJSON.cpp
  src/ripple/protocol/impl/STVar.cpp
  src/ripple/protocol/impl/STVar.h
  src/ripple/protocol/impl/STXChainBridge.cpp
  src/ripple/protocol/impl/TER.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/impl/XChainAttestations.cpp
  src/ripple/protocol/json_get_or_throw.h
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/AccountObjects.cpp
  src/ripple/rpc/handlers/LedgerEntry.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/test/app/XChain_test.cpp
  src/test/jtx/attester.h
  src/test/jtx/impl/attester.cpp
  src/test/jtx/impl/xchain_bridge.cpp
  src/test/jtx/xchain_bridge.h
  src/test/rpc/AccountObjects_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
  src/test/rpc/Subscribe_test.cpp
Labels: API Change, Amendment, Sidechains, Testable, Will Need Documentation

#4702 Revert ThreadName due to problems on Windows
  Builds/CMake/RippledCore.cmake
  src/ripple/app/ledger/impl/LedgerCleaner.cpp
  src/ripple/app/main/BasicApp.cpp
  src/ripple/app/main/GRPCServer.cpp
  src/ripple/app/main/LoadManager.cpp
  src/ripple/app/main/Main.cpp
  src/ripple/app/misc/SHAMapStoreImp.cpp
  src/ripple/app/reporting/ETLSource.cpp
  src/ripple/app/reporting/ReportingETL.cpp
  src/ripple/basics/impl/ThreadUtilities.cpp
  src/ripple/beast/core/CurrentThreadName.cpp
  src/ripple/beast/core/CurrentThreadName.h
  src/ripple/core/impl/Job.cpp
  src/ripple/core/impl/SNTPClock.cpp
  src/ripple/core/impl/Workers.cpp
  src/ripple/nodestore/backend/RocksDBFactory.cpp
  src/ripple/nodestore/impl/Database.cpp
  src/ripple/perflog/impl/PerfLogImp.cpp
  src/ripple/resource/impl/ResourceManager.cpp
  src/test/beast/beast_CurrentThreadName_test.cpp
  src/test/overlay/short_read_test.cpp
Labels: Passed

#4634 Match unit tests on start of test name, and split some test classes
  src/ripple/beast/unit_test/match.hpp
  src/test/app/NFTokenBurn_test.cpp
  src/test/app/NFToken_test.cpp
  src/test/app/Offer_test.cpp
Labels: Passed, Will Need Documentation

#4708 Remove two unused functions
  src/ripple/protocol/XChainAttestations.h
Labels: Passed

#4507 docs(BUILD): make it easier to find environment.md
  BUILD.md
Labels: Documentation

#4672 [TRIVIAL] Remove unused variable flagged by clang 14
  src/ripple/json/impl/Writer.cpp
Labels: Passed

#4574 Update comment about return value of LedgerHistory::fixIndex
  src/ripple/app/ledger/LedgerHistory.h
Labels: Documentation, Trivial

#4635 docs(overlay): add URL of blog post and clarify wording
  src/ripple/overlay/README.md
  src/ripple/overlay/ReduceRelayCommon.h
Labels: Passed

#4618 APIv2(gateway_balances, channel_authorize): update errors
  src/ripple/protocol/ErrorCodes.h
  src/ripple/protocol/impl/ErrorCodes.cpp
  src/ripple/rpc/handlers/GatewayBalances.cpp
  src/ripple/rpc/handlers/PayChanClaim.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/ripple/rpc/impl/RPCHelpers.h
  src/test/app/PayChan_test.cpp
  src/test/rpc/GatewayBalances_test.cpp
Labels: API Change, Clio Reviewed

#3839 Add ProtocolStart and GracefulClose messages
  Builds/CMake/RippledCore.cmake
  src/ripple/overlay/Message.h
  src/ripple/overlay/Peer.h
  src/ripple/overlay/README.md
  src/ripple/overlay/impl/InboundHandoff.cpp
  src/ripple/overlay/impl/InboundHandoff.h
  src/ripple/overlay/impl/Message.cpp
  src/ripple/overlay/impl/OverlayImpl.cpp
  src/ripple/overlay/impl/PeerImp.cpp
  src/ripple/overlay/impl/PeerImp.h
  src/ripple/overlay/impl/ProtocolMessage.h
  src/ripple/overlay/impl/ProtocolVersion.cpp
  src/ripple/proto/ripple.proto
  src/test/overlay/ProtocolVersion_test.cpp
Labels: Needs Discussion

#4566 Accept all valid currency codes in API
  src/ripple/net/impl/RPCCall.cpp
  src/ripple/protocol/impl/UintTypes.cpp
Labels: Passed, API Change, Bug, Clio Reviewed

#4628 Eliminate built-in SNTP support (fixes #4207):
  Builds/CMake/RippledCore.cmake
  Builds/levelization/results/ordering.txt
  cfg/rippled-example.cfg
  cfg/rippled-reporting.cfg
  src/ripple/app/main/Application.cpp
  src/ripple/app/main/Main.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/beast/clock/abstract_clock.h
  src/ripple/core/Config.h
  src/ripple/core/TimeKeeper.h
  src/ripple/core/impl/Config.cpp
  src/ripple/core/impl/SNTPClock.cpp
  src/ripple/core/impl/SNTPClock.h
  src/ripple/core/impl/TimeKeeper.cpp
  src/test/jtx/ManualTimeKeeper.h
  src/test/jtx/impl/ManualTimeKeeper.cpp
  src/test/overlay/compression_test.cpp
Labels: Passed, Bug, Tech Debt

#4731 [TRIVIAL] Fix build error: `uint` is not universally defined
  src/ripple/rpc/impl/RPCHelpers.h
Labels: Build System

#4410 Fix amendment majority flapping: use a more stable threshold for the number of votes required; when missing `STValidation`, use the last vote seen
  src/ripple/app/main/Application.cpp
  src/ripple/app/misc/AmendmentTable.h
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/impl/AmendmentTable.cpp
  src/test/app/AmendmentTable_test.cpp
Labels: Passed
