Repository XRPLF/rippled, pull requests merged in 2023-10, with the labels that each got.

#4720 Disallow the same bridge on one chain:
  src/ripple/app/tx/impl/XChainBridge.cpp
  src/test/app/XChain_test.cpp
Labels: Passed, XLS-38

#4662 [TRIVIAL] fix typo in SECURITY.md
  SECURITY.md
Labels: Passed

#4710 Reduce boilerplate in applySteps:
  src/ripple/app/tx/impl/applySteps.cpp
Labels: Passed, Tech Debt

#4721 fixDisallowIncomingV1
  src/ripple/app/tx/impl/SetTrust.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/SetTrust_test.cpp
Labels: Tx Change, Amendment

#4753 [TRIVIAL] Link compression in example cfg
  cfg/rippled-example.cfg
Labels: Documentation

#4741 Update API CHANGELOG for `XRPFees` changes
  API-CHANGELOG.md
  src/ripple/protocol/jss.h
  src/test/app/TxQ_test.cpp
Labels: Passed, Documentation

#4596 Reenable Windows CI build with Artifactory support
  .github/actions/build/action.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: Passed, CI

#4746 Fix output of remote step in nix workflow
  .github/workflows/nix.yml
Labels: Passed

#4743 [TRIVIAL] Remove incorrect assert
  src/ripple/app/paths/PathRequest.cpp
Labels: Passed

#4740 [TRIVIAL] docs: Fix broken `conanfile.py` link in build settings
  docs/build/conan.md
Labels: Build System, Documentation, Trivial

#4768 Call python to upgrade pip in Windows CI
  .github/workflows/windows.yml
Labels: CI, Bug, Dependencies

#4757 [TRIVIAL] docs(pull_request_template): add API Impact section
  .github/pull_request_template.md
Labels: Documentation

#4562 Replace some asserts in PeerFinder::Logic with LogicError
  src/ripple/peerfinder/impl/Logic.h
Labels: Passed, Tech Debt

#4559 Update hooks reserved error code name
  src/ripple/protocol/TER.h
Labels: API Change

#4636 `DID`: Decentralized identifiers (DIDs) (XLS-40):
  Builds/CMake/RippledCore.cmake
  src/ripple/app/tx/impl/DID.cpp
  src/ripple/app/tx/impl/DID.h
  src/ripple/app/tx/impl/DeleteAccount.cpp
  src/ripple/app/tx/impl/InvariantCheck.cpp
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/Indexes.h
  src/ripple/protocol/LedgerFormats.h
  src/ripple/protocol/Protocol.h
  src/ripple/protocol/SField.h
  src/ripple/protocol/TER.h
  src/ripple/protocol/TxFormats.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/Indexes.cpp
  src/ripple/protocol/impl/LedgerFormats.cpp
  src/ripple/protocol/impl/SField.cpp
  src/ripple/protocol/impl/TER.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/LedgerEntry.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/test/app/AccountDelete_test.cpp
  src/test/app/DID_test.cpp
  src/test/app/NFToken_test.cpp
  src/test/jtx.h
  src/test/jtx/did.h
  src/test/jtx/impl/did.cpp
  src/test/rpc/AccountObjects_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
Labels: Passed, API Change, Amendment, Will Need Documentation, Clio Reviewed

#4703 Add RPC for `server_definitions` to rippled
  API-CHANGELOG.md
  src/ripple/app/main/Main.cpp
  src/ripple/net/impl/RPCCall.cpp
  src/ripple/protocol/SField.h
  src/ripple/protocol/TER.h
  src/ripple/protocol/impl/TER.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/Handlers.h
  src/ripple/rpc/handlers/ServerInfo.cpp
  src/ripple/rpc/impl/Handler.cpp
  src/test/rpc/ServerInfo_test.cpp
Labels: API Change

#4737 Network ID logic should not be applied to pseudo-transactions
  src/ripple/app/tx/impl/Transactor.cpp
Labels: Bug

#4729 Clarify definition of "network health."
  src/ripple/app/misc/FeeEscalation.md
Labels: Documentation

#4759 Remove tx_history and ledger_header in API version 2
  API-CHANGELOG.md
  Builds/CMake/RippledCore.cmake
  src/ripple/perflog/impl/PerfLogImp.cpp
  src/ripple/perflog/impl/PerfLogImp.h
  src/ripple/rpc/handlers/LedgerHandler.h
  src/ripple/rpc/handlers/Version.h
  src/ripple/rpc/impl/Handler.cpp
  src/ripple/rpc/impl/Handler.h
  src/ripple/rpc/impl/RPCHelpers.h
  src/test/basics/PerfLog_test.cpp
  src/test/jtx/TestHelpers.h
  src/test/rpc/Handler_test.cpp
  src/test/rpc/LedgerHeader_test.cpp
  src/test/rpc/TransactionHistory_test.cpp
Labels: API Change, Clio Reviewed, API V2 Testing

#4788 Remove include <ranges>
  src/test/jtx/TestHelpers.h
Labels: Passed

#4694 Fix OfferCreate with tfFillOrKill if offer is better than open offer rate
  src/ripple/app/paths/Flow.cpp
  src/ripple/app/paths/Flow.h
  src/ripple/app/paths/RippleCalc.cpp
  src/ripple/app/paths/impl/PaySteps.cpp
  src/ripple/app/paths/impl/Steps.h
  src/ripple/app/paths/impl/StrandFlow.h
  src/ripple/app/tx/impl/CashCheck.cpp
  src/ripple/app/tx/impl/CreateOffer.cpp
  src/ripple/app/tx/impl/XChainBridge.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/AMMExtended_test.cpp
  src/test/app/Flow_test.cpp
  src/test/app/Offer_test.cpp
  src/test/app/PayStrand_test.cpp
  src/test/app/TheoreticalQuality_test.cpp
Labels: Passed, Bug, Amendment, Testable

#4677 [TRIVIAL] fix clang unused-but-set-variable warning
  src/ripple/app/rdb/backend/impl/PostgresDatabase.cpp
Labels: Tech Debt
