Repository XRPLF/rippled, pull requests merged in 2023-02, with the labels that each got.

#4346 `fixUnburnableNFToken`: Allow NFT to be burned when number of offers is greater than 500
  src/ripple/app/tx/impl/NFTokenBurn.cpp
  src/ripple/app/tx/impl/details/NFTokenUtils.cpp
  src/ripple/app/tx/impl/details/NFTokenUtils.h
  src/test/app/NFTokenBurn_test.cpp
Labels: Tx Change, Bug, Amendment, High Priority, Testable

#4247 `XRPFees`: Fee setting and handling improvements
  src/ripple/app/consensus/RCLConsensus.cpp
  src/ripple/app/ledger/Ledger.cpp
  src/ripple/app/misc/FeeVote.h
  src/ripple/app/misc/FeeVoteImpl.cpp
  src/ripple/app/misc/LoadFeeTrack.h
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/TxQ.h
  src/ripple/app/misc/impl/LoadFeeTrack.cpp
  src/ripple/app/misc/impl/TxQ.cpp
  src/ripple/app/tx/applySteps.h
  src/ripple/app/tx/impl/ApplyContext.cpp
  src/ripple/app/tx/impl/ApplyContext.h
  src/ripple/app/tx/impl/Change.cpp
  src/ripple/app/tx/impl/Change.h
  src/ripple/app/tx/impl/DeleteAccount.cpp
  src/ripple/app/tx/impl/DeleteAccount.h
  src/ripple/app/tx/impl/Escrow.cpp
  src/ripple/app/tx/impl/Escrow.h
  src/ripple/app/tx/impl/SetRegularKey.cpp
  src/ripple/app/tx/impl/SetRegularKey.h
  src/ripple/app/tx/impl/Transactor.cpp
  src/ripple/app/tx/impl/Transactor.h
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/basics/FeeUnits.h
  src/ripple/core/Config.h
  src/ripple/ledger/ReadView.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/SField.h
  src/ripple/protocol/SystemParameters.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/LedgerFormats.cpp
  src/ripple/protocol/impl/SField.cpp
  src/ripple/protocol/impl/STValidation.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/NoRippleCheck.cpp
  src/ripple/rpc/impl/TransactionSign.cpp
  src/test/app/AccountDelete_test.cpp
  src/test/app/FeeVote_test.cpp
  src/test/app/LoadFeeTrack_test.cpp
  src/test/app/PseudoTx_test.cpp
  src/test/app/TxQ_test.cpp
  src/test/basics/FeeUnits_test.cpp
  src/test/ledger/Invariants_test.cpp
  src/test/rpc/AccountTx_test.cpp
  src/test/rpc/Subscribe_test.cpp
Labels: Passed, Bug, Amendment, High Priority, Sidechain, Testable, Will Need Documentation

#4382 Revise CONTRIBUTING
  CONTRIBUTING.md
Labels: Documentation, Trivial

#4407 Update dependency: grpc
  conanfile.py
Labels: Build System, Dependencies

#4409 Update documented pathfinding configuration defaults:
  cfg/rippled-example.cfg
Labels: Passed, Documentation, Trivial

#4380 [Amendment] Fix 3 issues around NFToken offer acceptance
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
  src/ripple/app/tx/impl/NFTokenCreateOffer.cpp
  src/ripple/ledger/View.h
  src/test/app/NFToken_test.cpp
Labels: Passed, Bug, Amendment, Testable

#4403 Prevent brokered sale of NFToken to owner (fix #4374)
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
  src/test/app/NFToken_test.cpp
Labels: Passed, Bug, Amendment, Testable, Will Need Documentation

#4413 Resolve a couple of Github Action CI annoyances:
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: CI

#4421 README: Add a few source code starting points
  README.md
Labels: Documentation, Trivial

#4430 Fix Conan version constraint in workflows
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: CI, Build System, Trivial

#4435 Update package building scripts and images to use Conan
  .gitignore
  Builds/CMake/RippledRelease.cmake
  Builds/containers/centos-builder/Dockerfile
  Builds/containers/centos-builder/centos_setup.sh
  Builds/containers/centos-builder/extras.sh
  Builds/containers/gitlab-ci/pkgbuild.yml
  Builds/containers/gitlab-ci/push_to_artifactory.sh
  Builds/containers/gitlab-ci/smoketest.sh
  Builds/containers/packaging/dpkg/build_dpkg.sh
  Builds/containers/packaging/dpkg/debian/control
  Builds/containers/packaging/dpkg/debian/rippled.install
  Builds/containers/packaging/dpkg/debian/rules
  Builds/containers/packaging/rpm/build_rpm.sh
  Builds/containers/packaging/rpm/rippled.spec
  Builds/containers/shared/build_deps.sh
  Builds/containers/shared/install_boost.sh
  Builds/containers/shared/install_cmake.sh
  Builds/containers/ubuntu-builder/Dockerfile
  Builds/containers/ubuntu-builder/ubuntu_setup.sh
  src/ripple/protocol/impl/BuildInfo.cpp
Labels: Passed
