Repository XRPLF/rippled, pull requests merged in 2023-05, with the labels that each got.

#4404 API does not accept seed or public key for account
  src/ripple/app/main/Main.cpp
  src/ripple/net/impl/RPCCall.cpp
  src/ripple/rpc/handlers/AccountChannels.cpp
  src/ripple/rpc/handlers/AccountCurrenciesHandler.cpp
  src/ripple/rpc/handlers/AccountInfo.cpp
  src/ripple/rpc/handlers/AccountLines.cpp
  src/ripple/rpc/handlers/AccountObjects.cpp
  src/ripple/rpc/handlers/AccountOffers.cpp
  src/ripple/rpc/handlers/DepositAuthorized.cpp
  src/ripple/rpc/handlers/GatewayBalances.cpp
  src/ripple/rpc/handlers/NoRippleCheck.cpp
  src/ripple/rpc/handlers/OwnerInfo.cpp
  src/test/rpc/AccountCurrencies_test.cpp
  src/test/rpc/AccountInfo_test.cpp
  src/test/rpc/AccountLinesRPC_test.cpp
  src/test/rpc/AccountObjects_test.cpp
  src/test/rpc/AccountOffers_test.cpp
  src/test/rpc/NoRippleCheck_test.cpp
  src/test/rpc/OwnerInfo_test.cpp
  src/test/rpc/RPCCall_test.cpp
Labels: Passed, API Change, Will Need Documentation

#4447 Add `nftoken_id`, `nftoken_ids` and `offer_id` meta fields into NFT `Tx` responses
  Builds/CMake/RippledCore.cmake
  src/ripple/protocol/jss.h
  src/ripple/rpc/NFTSyntheticSerializer.h
  src/ripple/rpc/NFTokenID.h
  src/ripple/rpc/NFTokenOfferID.h
  src/ripple/rpc/handlers/AccountTx.cpp
  src/ripple/rpc/handlers/Tx.cpp
  src/ripple/rpc/impl/NFTSyntheticSerializer.cpp
  src/ripple/rpc/impl/NFTokenID.cpp
  src/ripple/rpc/impl/NFTokenOfferID.cpp
  src/test/app/NFToken_test.cpp
Labels: API Change, Feature Request, Testable, Will Need Documentation

#4527 Ensure that switchover vars are initialized before use:
  src/ripple/basics/IOUAmount.h
  src/ripple/basics/impl/IOUAmount.cpp
  src/ripple/protocol/STAmount.h
  src/ripple/protocol/impl/STAmount.cpp
Labels: Passed, Bug

#4514 Update BUILD.md
  BUILD.md
Labels: Documentation, Trivial
