Repository XRPLF/rippled, pull requests merged in 2023-04, with the labels that each got.

#4352 Add NFTokenPages to account_objects RPC
  src/ripple/rpc/handlers/AccountObjects.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/ripple/rpc/impl/RPCHelpers.h
  src/test/rpc/AccountLinesRPC_test.cpp
  src/test/rpc/AccountObjects_test.cpp
Labels: API Change, Bug, Testable, Will Need Documentation

#4320 add jss fields used by clio `nft_info`
  src/ripple/protocol/jss.h
Labels: Passed, Tech Debt

#4218 Introduce a slab-based memory allocator and optimize SHAMapItem
  src/ripple/app/ledger/Ledger.cpp
  src/ripple/app/ledger/Ledger.h
  src/ripple/app/ledger/LedgerHistory.cpp
  src/ripple/app/ledger/LedgerHistory.h
  src/ripple/app/ledger/impl/LedgerToJson.cpp
  src/ripple/app/rdb/impl/UnitaryShard.cpp
  src/ripple/nodestore/impl/DecodedBlob.cpp
  src/ripple/protocol/impl/TxMeta.cpp
  src/ripple/shamap/SHAMap.h
  src/ripple/shamap/impl/SHAMap.cpp
Labels: Tech Debt, Resource Improvement, Testable

#4370 Add NetworkID field to transactions to help prevent replay attacks on and from side-chains
  Builds/CMake/RippledCore.cmake
  src/ripple/app/tx/impl/Transactor.cpp
  src/ripple/core/Config.h
  src/ripple/core/ConfigSections.h
  src/ripple/core/impl/Config.cpp
  src/ripple/protocol/SField.h
  src/ripple/protocol/TER.h
  src/ripple/protocol/impl/SField.cpp
  src/ripple/protocol/impl/TER.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/jss.h
  src/test/app/NetworkID_test.cpp
  src/test/core/Config_test.cpp
  src/test/jtx/impl/Env.cpp
Labels: Passed, Feature Request, Testable, Will Need Documentation

#4496 Fix the fix for std::result_of
  BUILD.md
Labels: Passed

#4472 Add install instructions for package managers
  docs/build/install.md
Labels: Passed

#4489 If present, set quorum based on command line.
  src/ripple/app/misc/impl/ValidatorList.cpp
  src/test/app/ValidatorList_test.cpp
Labels: Passed

#4454 Expand Linux test matrix
  .github/actions/build/action.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: Passed, CI, Build System

#4508 Fix typo
  SECURITY.md
Labels: Trivial

#4498 Update environment.md
  docs/build/environment.md
Labels: Build System, Documentation
