Repository XRPLF/rippled, pull requests merged in 2023-06, with the labels that each got.

#4555 [TRIVIAL] Add missing includes
  src/ripple/basics/StringUtilities.h
  src/ripple/basics/base64.h
  src/ripple/json/impl/json_reader.cpp
Labels: Passed, Build System, Trivial

#4536 fix node size estimation
  src/ripple/core/impl/Config.cpp
Labels: Passed, Bug

#4512 `fixReducedOffersV1`: curtail the occurrence of order books that are blocked by reduced offers
  Builds/CMake/RippledCore.cmake
  src/ripple/app/paths/impl/BookStep.cpp
  src/ripple/app/tx/impl/CreateOffer.cpp
  src/ripple/app/tx/impl/OfferStream.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/Quality.h
  src/ripple/protocol/STAmount.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/Quality.cpp
  src/ripple/protocol/impl/STAmount.cpp
  src/test/app/Offer_test.cpp
  src/test/app/ReducedOffer_test.cpp
Labels: Passed, Amendment

#4427 Add RPC/WS ports to server_info
  src/ripple/app/main/Application.cpp
  src/ripple/app/main/Application.h
  src/ripple/app/main/GRPCServer.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/protocol/jss.h
  src/test/rpc/ServerInfo_test.cpp
Labels: Passed, API Change, Will Need Documentation

#4556 Use Artifactory remote in nix workflow
  .github/workflows/nix.yml
Labels: CI, Dependencies

#4567 Typedfield has bad move constructor
  src/ripple/protocol/SField.h
  src/ripple/protocol/impl/SField.cpp
Labels: Passed

#4553 XLS-39 Clawback:
  Builds/CMake/RippledCore.cmake
  src/ripple/app/tx/impl/Clawback.cpp
  src/ripple/app/tx/impl/Clawback.h
  src/ripple/app/tx/impl/InvariantCheck.cpp
  src/ripple/app/tx/impl/InvariantCheck.h
  src/ripple/app/tx/impl/SetAccount.cpp
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/LedgerFormats.h
  src/ripple/protocol/TxFlags.h
  src/ripple/protocol/TxFormats.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/jss.h
  src/test/app/Clawback_test.cpp
  src/test/jtx/flags.h
  src/test/jtx/impl/trust.cpp
  src/test/jtx/trust.h
  src/test/rpc/AccountSet_test.cpp
Labels: Passed, Amendment

#4473 replace hand-rolled lexicalCast
  src/ripple/app/rdb/backend/detail/impl/Node.cpp
  src/ripple/beast/core/LexicalCast.h
Labels: Passed, Tech Debt

#4485 Fix package definition for Conan
  Builds/CMake/RippledCore.cmake
  conanfile.py
  src/ripple/protocol/impl/secp256k1.h
  src/secp256k1/CMakeLists.txt
  src/secp256k1/src/bench_ecdh.c
  src/secp256k1/src/bench_internal.c
  src/secp256k1/src/bench_recover.c
  src/secp256k1/src/bench_schnorr_verify.c
  src/secp256k1/src/bench_sign.c
  src/secp256k1/src/bench_verify.c
  src/secp256k1/src/gen_context.c
  src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c
  src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.h
  src/secp256k1/src/java/org_bitcoin_Secp256k1Context.c
  src/secp256k1/src/java/org_bitcoin_Secp256k1Context.h
  src/secp256k1/src/modules/ecdh/main_impl.h
  src/secp256k1/src/modules/recovery/main_impl.h
  src/secp256k1/src/secp256k1.c
  src/secp256k1/src/tests.c
  src/secp256k1/src/tests_exhaustive.c
Labels: Passed, Build System

#4244 remove deprecated fields in ledger command, fix for #3214
  src/ripple/app/ledger/impl/LedgerToJson.cpp
  src/ripple/protocol/jss.h
  src/test/app/SHAMapStore_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
Labels: Passed, API Change, Tech Debt, Testable, Will Need Documentation

#4516 Trivial: Rename `ServerHandlerImp` to `ServerHandler`
  Builds/CMake/RippledCore.cmake
  src/ripple/rpc/ServerHandler.h
  src/ripple/rpc/impl/ServerHandler.cpp
  src/ripple/rpc/impl/ServerHandlerImp.h
Labels: Passed, Tech Debt, Trivial

#4571 Added error messages on AccountTx
  src/ripple/rpc/handlers/AccountTx.cpp
  src/test/rpc/AccountTx_test.cpp
Labels: API Change, Will Need Documentation

#4239 Change enum values to be powers of two (fix #3417)
  src/ripple/rpc/impl/Handler.h
Labels: Tech Debt

#4597 Cancel overridden workflows
  .github/workflows/doxygen.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
Labels: Passed

#4585 account_info with Invalid signer list returns invalid params
  src/ripple/rpc/handlers/AccountInfo.cpp
  src/test/rpc/AccountInfo_test.cpp
Labels: API Change, Will Need Documentation
