Repository XRPLF/rippled, pull requests merged in 2023-07, with the labels that each got.

#4598 [TRIVIAL] Update checkout action version to resolve warning
  .github/workflows/clang-format.yml
  .github/workflows/levelization.yml
Labels: Passed, CI

#4603 Add binary hardening compile and link flags
  Builds/CMake/RippledCompiler.cmake
Labels: Passed

#4243 Change the return type of mulDiv to std::optional
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/TxQ.h
  src/ripple/app/misc/impl/LoadFeeTrack.cpp
  src/ripple/app/misc/impl/TxQ.cpp
  src/ripple/basics/FeeUnits.h
  src/ripple/basics/impl/mulDiv.cpp
  src/ripple/basics/mulDiv.h
  src/ripple/rpc/handlers/Fee1.cpp
  src/ripple/rpc/impl/TransactionSign.cpp
  src/test/app/TxQ_test.cpp
  src/test/basics/FeeUnits_test.cpp
  src/test/basics/mulDiv_test.cpp
Labels: Passed

#4552 Fix: returning invalidParams instead of unknownOption error code in ledger_entry (#4303)
  src/ripple/rpc/handlers/LedgerEntry.cpp
  src/test/rpc/LedgerRPC_test.cpp
Labels: API Change, Bug, Will Need Documentation

#4589 docs(CONTRIBUTING): push beta releases to `release`
  CONTRIBUTING.md
Labels: Documentation, Trivial

#4615 Adapt to change in Conan recipe for NuDB
  CMakeLists.txt
Labels: Passed

#4595 Update dependencies
  .github/actions/dependencies/action.yml
  .github/workflows/macos.yml
  BUILD.md
  conanfile.py
  external/snappy/conandata.yml
  external/snappy/patches/1.1.10-0001-fix-inlining-failure.patch
  external/snappy/patches/1.1.10-0003-fix-clobber-list-older-llvm.patch
  src/ripple/basics/RangeSet.h
  src/ripple/consensus/Consensus.h
  src/ripple/json/impl/json_reader.cpp
  src/ripple/net/HTTPClient.h
  src/ripple/overlay/impl/Handshake.cpp
  src/ripple/overlay/impl/PeerImp.cpp
  src/ripple/rpc/impl/ServerHandler.cpp
  src/ripple/rpc/impl/WSInfoSub.h
  src/test/app/LedgerLoad_test.cpp
  src/test/jtx/TrustedPublisherServer.h
Labels: Build System, Dependencies

#4617 Rename `allowClawback` flag to `allowTrustLineClawback`
  src/ripple/app/tx/impl/Clawback.cpp
  src/ripple/app/tx/impl/SetAccount.cpp
  src/ripple/protocol/LedgerFormats.h
  src/ripple/protocol/TxFlags.h
  src/ripple/rpc/handlers/AccountInfo.cpp
  src/test/app/Clawback_test.cpp
  src/test/jtx/flags.h
  src/test/rpc/AccountInfo_test.cpp
  src/test/rpc/AccountSet_test.cpp
Labels: Passed, Trivial

#4623 BUILD: list steps after dependencies update
  BUILD.md
Labels: Trivial
