Repository XRPLF/rippled, pull requests merged in 2023-03, with the labels that each got.

#4460 docs: security bug bounty acknowledgements
  RELEASENOTES.md
Labels: Trivial

#4458 Do not attempt to acquire missing data from peer network in
  src/ripple/app/ledger/Ledger.cpp
  src/ripple/shamap/Family.h
  src/ripple/shamap/NodeFamily.h
  src/ripple/shamap/ShardFamily.h
  src/ripple/shamap/impl/NodeFamily.cpp
  src/ripple/shamap/impl/SHAMap.cpp
  src/ripple/shamap/impl/ShardFamily.cpp
  src/test/shamap/common.h
Labels: Passed

#4411 Replace compare() with the three-way comparison operator in base_uint, Issue and Book
  src/ripple/app/tx/impl/details/NFTokenUtils.cpp
  src/ripple/basics/base_uint.h
  src/ripple/protocol/Book.h
  src/ripple/protocol/Issue.h
  src/ripple/protocol/impl/Book.cpp
  src/ripple/protocol/impl/Issue.cpp
  src/test/basics/base_uint_test.cpp
Labels: Passed

#4328 Allow port numbers be be specified using a either a colon or a space
  src/ripple/core/impl/Config.cpp
  src/ripple/net/impl/RPCCall.cpp
  src/ripple/rpc/handlers/Connect.cpp
  src/test/core/Config_test.cpp
Labels: Passed, Testable, Will Need Documentation

#4293 Rectify the import paths of boost::function_output_iterator
  src/ripple/overlay/impl/ProtocolVersion.cpp
  src/test/csf/Tx.h
Labels: Passed

#4355 fix(gateway_balances): handle overflow exception
  src/ripple/rpc/handlers/GatewayBalances.cpp
  src/test/rpc/GatewayBalances_test.cpp
Labels: Bug, Testable, Will Need Documentation

#4420 fix(ValidatorSite): handle rare null pointer dereference in timeout
  src/ripple/app/misc/impl/ValidatorSite.cpp
Labels: Passed

#4353 Eliminate memory allocation from critical path:
  Builds/CMake/RippledCore.cmake
  src/ripple/nodestore/backend/CassandraFactory.cpp
  src/ripple/nodestore/backend/NuDBFactory.cpp
  src/ripple/nodestore/backend/RocksDBFactory.cpp
  src/ripple/nodestore/impl/EncodedBlob.cpp
  src/ripple/nodestore/impl/EncodedBlob.h
  src/test/nodestore/Basics_test.cpp
Labels: Passed, Request for Comments, Food for Thought, Resource Improvement, Testable

#4361 RPC commands understand markers derived from all ledger object types
  src/ripple/rpc/handlers/AccountChannels.cpp
  src/ripple/rpc/handlers/AccountLines.cpp
  src/ripple/rpc/handlers/AccountOffers.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/ripple/rpc/impl/RPCHelpers.h
  src/test/rpc/AccountLinesRPC_test.cpp
Labels: Passed, API Change, Bug, Testable

#4406 `fixNFTokenRemint`: prevent NFT re-mint:
  src/ripple/app/tx/impl/DeleteAccount.cpp
  src/ripple/app/tx/impl/NFTokenMint.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/SField.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/LedgerFormats.cpp
  src/ripple/protocol/impl/SField.cpp
  src/test/app/NFTokenBurn_test.cpp
  src/test/app/NFTokenDir_test.cpp
  src/test/app/NFToken_test.cpp
  src/test/jtx/impl/token.cpp
  src/test/jtx/token.h
Labels: Passed, Bug, Amendment, Testable, Will Need Documentation

#4470 Proposed 1.10.1
  RELEASENOTES.md
  src/ripple/protocol/impl/BuildInfo.cpp
Labels: Trivial

#4449 Make it easy for projects to depend on libxrpl
  Builds/CMake/RippledCore.cmake
  conanfile.py
  docs/build/depend.md
Labels: Passed

#4401 Fix a case where ripple::Expected returned a json array, not a value
  src/ripple/basics/Expected.h
  src/test/basics/Expected_test.cpp
Labels: Passed, Bug

#4291 Add the ability to mark amendments as obsolete
  src/ripple/app/misc/AmendmentTable.h
  src/ripple/app/misc/impl/AmendmentTable.cpp
  src/ripple/app/rdb/Wallet.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/AmendmentTable_test.cpp
  src/test/rpc/Feature_test.cpp
Labels: Passed, Tech Debt, Amendment, Testable, Will Need Documentation

#4319 Always create the FeeSettings object in genesis ledger
  cfg/rippled-example.cfg
  cfg/rippled-reporting.cfg
  src/ripple/app/ledger/Ledger.cpp
  src/ripple/app/ledger/Ledger.h
  src/ripple/app/ledger/impl/BuildLedger.cpp
  src/ripple/app/ledger/impl/InboundLedger.cpp
  src/ripple/app/main/Application.cpp
  src/ripple/app/misc/FeeVote.h
  src/ripple/app/misc/FeeVoteImpl.cpp
  src/ripple/app/reporting/ReportingETL.cpp
  src/ripple/core/Config.h
  src/ripple/core/ConfigSections.h
  src/ripple/core/impl/Config.cpp
  src/ripple/ledger/ReadView.h
  src/ripple/ledger/impl/ReadView.cpp
  src/ripple/nodestore/impl/Shard.cpp
  src/ripple/protocol/Rules.h
  src/ripple/protocol/SystemParameters.h
  src/ripple/protocol/impl/Rules.cpp
  src/ripple/rpc/impl/TransactionSign.cpp
  src/test/app/FeeVote_test.cpp
  src/test/app/LedgerHistory_test.cpp
  src/test/app/LedgerLoad_test.cpp
  src/test/app/LoadFeeTrack_test.cpp
  src/test/app/NFToken_test.cpp
  src/test/app/Offer_test.cpp
  src/test/app/RCLValidations_test.cpp
  src/test/app/TxQ_test.cpp
  src/test/jtx/impl/envconfig.cpp
  src/test/rpc/LedgerClosed_test.cpp
  src/test/rpc/LedgerData_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
  src/test/rpc/LedgerRequestRPC_test.cpp
  src/test/rpc/ReportingETL_test.cpp
Labels: Passed, Tech Debt, Sidechain, Testable, Will Need Documentation

#4450 Link to BUILD.md from Builds/README.md
  Builds/README.md
Labels: Trivial

#4448 Remove Coil from example [validator_list_sites]
  cfg/validators-example.txt
Labels: Trivial

#4400 Log exception messages in several locations
  src/ripple/app/consensus/RCLConsensus.cpp
  src/ripple/app/ledger/ConsensusTransSetSF.cpp
  src/ripple/app/ledger/Ledger.cpp
  src/ripple/app/ledger/Ledger.h
  src/ripple/app/ledger/impl/BuildLedger.cpp
  src/ripple/app/ledger/impl/LedgerMaster.cpp
  src/ripple/app/ledger/impl/LedgerToJson.cpp
  src/ripple/app/ledger/impl/OpenLedger.cpp
  src/ripple/app/misc/Manifest.h
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/impl/Manifest.cpp
  src/ripple/app/misc/impl/ValidatorSite.cpp
  src/ripple/app/tx/impl/apply.cpp
  src/ripple/basics/impl/make_SSLContext.cpp
  src/ripple/overlay/impl/PeerImp.cpp
  src/ripple/rpc/handlers/PayChanClaim.cpp
  src/ripple/shamap/impl/SHAMap.cpp
Labels: Passed

#4459 Parse flags in account_info method
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/AccountInfo.cpp
  src/test/rpc/AccountInfo_test.cpp
Labels: API Change, Will Need Documentation

#4398 fix: Ledger data returns an empty list (instead of null) when all entries are filtered out
  src/ripple/rpc/handlers/LedgerData.cpp
  src/test/rpc/LedgerData_test.cpp
Labels: API Change, Good First Issue, Testable, Will Need Documentation
