Repository XRPLF/rippled, pull requests merged in 2023-11, with the labels that each got.

#4785 Fix unit test api_version to enable api_version 2
  src/ripple/net/RPCCall.h
  src/ripple/net/impl/RPCCall.cpp
  src/test/jtx/impl/Env.cpp
  src/test/jtx/impl/utility.cpp
  src/test/jtx/utility.h
  src/test/rpc/RPCCall_test.cpp
Labels: API Change, Clio Reviewed, API V2 Testing

#4798 fix: check for valid public key in attestations
  src/ripple/app/tx/impl/XChainBridge.cpp
  src/test/app/XChain_test.cpp
Labels: Passed

#4775 Unify JSON serialization format of transactions
  API-CHANGELOG.md
  src/ripple/app/ledger/LedgerMaster.h
  src/ripple/app/ledger/LedgerToJson.h
  src/ripple/app/ledger/impl/LedgerMaster.cpp
  src/ripple/app/ledger/impl/LedgerToJson.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/Transaction.h
  src/ripple/app/misc/impl/Transaction.cpp
  src/ripple/basics/chrono.h
  src/ripple/core/TimeKeeper.h
  src/ripple/protocol/STBase.h
  src/ripple/protocol/STObject.h
  src/ripple/protocol/STTx.h
  src/ripple/protocol/impl/STTx.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/AMMInfo.cpp
  src/ripple/rpc/handlers/AccountTx.cpp
  src/ripple/rpc/handlers/LedgerHandler.cpp
  src/ripple/rpc/handlers/SignFor.cpp
  src/ripple/rpc/handlers/SignHandler.cpp
  src/ripple/rpc/handlers/Submit.cpp
  src/ripple/rpc/handlers/SubmitMultiSigned.cpp
  src/ripple/rpc/handlers/TransactionEntry.cpp
  src/ripple/rpc/handlers/Tx.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/ripple/rpc/impl/RPCHelpers.h
  src/ripple/rpc/impl/TransactionSign.cpp
  src/ripple/rpc/impl/TransactionSign.h
  src/test/rpc/AccountTx_test.cpp
  src/test/rpc/JSONRPC_test.cpp
  src/test/rpc/Subscribe_test.cpp
  src/test/rpc/TransactionEntry_test.cpp
  src/test/rpc/Transaction_test.cpp
Labels: API Change, Testable, Clio Reviewed, API V2 Testing

#4760 Optimize calculation of close time to avoid impasse and minimize gratuitous proposal changes
  src/ripple/consensus/Consensus.h
Labels: Passed, Performance/Resource Improvement
