Repository XRPLF/rippled, pull requests merged in 2024-03, with the labels that each got.

#4607 Remove default constructor from SecretKey class
  src/ripple/app/consensus/RCLConsensus.cpp
  src/ripple/app/main/Application.cpp
  src/ripple/app/main/Application.h
  src/ripple/app/misc/Manifest.h
  src/ripple/app/misc/NegativeUNLVote.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/ValidatorKeys.h
  src/ripple/app/misc/ValidatorList.h
  src/ripple/app/misc/impl/Manifest.cpp
  src/ripple/app/misc/impl/ValidatorKeys.cpp
  src/ripple/app/misc/impl/ValidatorList.cpp
  src/ripple/basics/impl/contract.cpp
  src/ripple/json/impl/json_reader.cpp
  src/ripple/overlay/impl/OverlayImpl.cpp
  src/ripple/overlay/impl/PeerImp.cpp
  src/ripple/protocol/PublicKey.h
  src/ripple/protocol/SecretKey.h
  src/ripple/protocol/impl/PublicKey.cpp
  src/ripple/rpc/handlers/Manifest.cpp
  src/ripple/rpc/handlers/PayChanClaim.cpp
  src/ripple/rpc/handlers/ValidatorInfo.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/ripple/rpc/impl/RPCHelpers.h
  src/ripple/rpc/impl/TransactionSign.cpp
  src/test/app/LedgerLoad_test.cpp
  src/test/app/LedgerReplay_test.cpp
  src/test/app/Manifest_test.cpp
  src/test/app/ValidatorKeys_test.cpp
  src/test/app/ValidatorList_test.cpp
  src/test/app/ValidatorSite_test.cpp
  src/test/app/XChain_test.cpp
  src/test/consensus/NegativeUNL_test.cpp
  src/test/jtx/Account.h
  src/test/jtx/Env_test.cpp
  src/test/overlay/reduce_relay_test.cpp
  src/test/protocol/PublicKey_test.cpp
  src/test/protocol/STObject_test.cpp
  src/test/protocol/SecretKey_test.cpp
  src/test/rpc/KeyGeneration_test.cpp
Labels: Passed, Tech Debt, Perf impact not expected

#4327 Fast base58 codec
  Builds/CMake/RippledCore.cmake
  src/ripple/protocol/impl/b58_utils.h
  src/ripple/protocol/impl/token_errors.h
  src/ripple/protocol/impl/tokens.cpp
  src/ripple/protocol/tokens.h
  src/test/basics/base58_test.cpp
Labels: Passed, Testable, Perf SignedOff

#4781 feat: add user version of `feature` RPC
  API-CHANGELOG.md
  src/ripple/app/misc/AmendmentTable.h
  src/ripple/app/misc/impl/AmendmentTable.cpp
  src/ripple/rpc/handlers/Feature1.cpp
  src/ripple/rpc/impl/Handler.cpp
  src/test/app/AmendmentTable_test.cpp
  src/test/rpc/Feature_test.cpp
Labels: Passed, API Change, Feature Request, Clio Reviewed, Perf Test Desired (Optional)

#4947 Embed patched recipe for RocksDB 6.29.5
  .github/actions/dependencies/action.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
  BUILD.md
  external/rocksdb/conandata.yml
  external/rocksdb/conanfile.py
  external/rocksdb/patches/6.29.5-0001-add-include-cstdint-for-gcc-13.patch
  external/rocksdb/patches/6.29.5-0002-exclude-thirdparty.patch
Labels: Passed

#4890 fix: order book update variable swap:
  src/ripple/app/ledger/OrderBookDB.cpp
Labels: Passed, Bug, Testable, Perf Test Desired (Optional)

#4893 Upgrade to xxhash 0.8.2 as conan dependency, enable SIMD hashing
  Builds/CMake/RippledCore.cmake
  CMakeLists.txt
  conanfile.py
  src/ripple/beast/hash/impl/xxhash.cpp
  src/ripple/beast/hash/impl/xxhash.h
  src/ripple/beast/hash/xxhasher.h
Labels: Passed, Perf SignedOff

#4949 Update remaining actions
  .github/workflows/clang-format.yml
  .github/workflows/doxygen.yml
  .github/workflows/levelization.yml
  .github/workflows/nix.yml
Labels: Passed

#4887 test: env unit test RPC errors return a unique result:
  src/ripple/protocol/TER.h
  src/ripple/protocol/impl/TER.cpp
  src/test/app/MultiSign_test.cpp
  src/test/app/Regression_test.cpp
  src/test/app/ValidatorSite_test.cpp
  src/test/jtx/Env.h
  src/test/jtx/Env_test.cpp
  src/test/jtx/impl/Env.cpp
  src/test/net/DatabaseDownloader_test.cpp
  src/test/protocol/Memo_test.cpp
Labels: Passed, Perf impact not expected

#4955 RIPD-1847 fix select query condition
  src/ripple/app/rdb/backend/detail/impl/Node.cpp
Labels: Passed

#4950 Add the`fixEmptyDID` amendment
  src/ripple/app/tx/impl/DID.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/DID_test.cpp
Labels: Passed, Amendment

#4944 Enforce no duplicate slots from incoming connections
  src/ripple/peerfinder/impl/Logic.h
  src/test/peerfinder/PeerFinder_test.cpp
Labels: Passed, Bug, Perf impact not expected

#4903 Remove zaphod.alloy.ee from bootstrap
  cfg/rippled-example.cfg
  cfg/rippled-reporting.cfg
  src/ripple/overlay/impl/OverlayImpl.cpp
Labels: Passed, Will Need Documentation

#4833 Write proper `forAllApiVersions` used in NetworkOPs.cpp
  Builds/CMake/RippledCore.cmake
  Builds/levelization/results/ordering.txt
  src/ripple/app/ledger/BookListeners.cpp
  src/ripple/app/ledger/BookListeners.h
  src/ripple/app/ledger/OrderBookDB.h
  src/ripple/app/ledger/impl/LedgerToJson.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/json/MultivarJson.h
  src/ripple/protocol/ApiVersion.h
  src/ripple/protocol/MultiApiJson.h
  src/ripple/rpc/impl/RPCHelpers.h
  src/ripple/rpc/impl/ServerHandler.cpp
  src/test/app/PayChan_test.cpp
  src/test/json/MultivarJson_test.cpp
  src/test/jtx/Env.h
  src/test/protocol/ApiVersion_test.cpp
  src/test/protocol/MultiApiJson_test.cpp
  src/test/rpc/AccountTx_test.cpp
  src/test/rpc/GatewayBalances_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
  src/test/rpc/LedgerRequestRPC_test.cpp
  src/test/rpc/NoRipple_test.cpp
  src/test/rpc/RPCCall_test.cpp
  src/test/rpc/TransactionEntry_test.cpp
  src/test/rpc/Transaction_test.cpp
  src/test/rpc/Version_test.cpp
Labels: Passed, Perf impact not expected

#4763 Don't reach consensus as fast if no other proposals seen.
  src/ripple/consensus/Consensus.cpp
  src/ripple/consensus/Consensus.h
  src/ripple/consensus/ConsensusParms.h
  src/test/consensus/Consensus_test.cpp
Labels: Passed, Perf Test Desired (Optional)

#4933 Fix sidechain reward share rounding with new number class
  src/ripple/app/tx/impl/XChainBridge.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
Labels: Passed, Bug, Amendment
