Repository XRPLF/rippled, pull requests merged in 2024-02, with the labels that each got.

#4871 Windows CI unit tests need to pass
  .github/workflows/windows.yml
Labels: Passed, CI, Perf impact not expected

#4831 Use platform-agnostic library names in Conan recipe
  conanfile.py
  src/secp256k1/src/CMakeLists.txt
Labels: Passed, Build System, Libraries, Dependencies, Will Need Documentation, Perf impact not expected

#4767 `fixNFTokenReserve`: Throw error when NFT buyer does not meet reserve requirement
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
  src/ripple/app/tx/impl/NFTokenAcceptOffer.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/NFToken_test.cpp
Labels: Passed, Bug, Amendment, Perf impact not expected

#4885 Headers needed in Conan package to build xbridge witness server
  Builds/CMake/RippledCore.cmake
Labels: Passed, Build System, Libraries, Perf impact not expected

#4728 Validate grpc port info in GRPCServer ctor
  src/ripple/app/main/GRPCServer.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/core/ConfigSections.h
  src/ripple/rpc/impl/ServerHandler.cpp
  src/test/jtx/envconfig.h
  src/test/jtx/impl/envconfig.cpp
  src/test/rpc/ReportingETL_test.cpp
  src/test/rpc/ServerInfo_test.cpp
Labels: Passed, Testable, Will Need Documentation, Perf impact not expected

#4906 Add STObject constructor to explicitly set inner object template
  src/ripple/app/misc/impl/AMMUtils.cpp
  src/ripple/app/tx/impl/AMMBid.cpp
  src/ripple/app/tx/impl/AMMVote.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/SOTemplate.h
  src/ripple/protocol/STObject.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/InnerObjectFormats.cpp
  src/ripple/protocol/impl/STObject.cpp
  src/ripple/rpc/handlers/AMMInfo.cpp
  src/test/app/AMM_test.cpp
  src/test/jtx/AMM.h
  src/test/jtx/impl/AMM.cpp
Labels: Bug, Amendment, Testable, Perf impact not expected

#4917 Improve object lifetime management when creating temporary Rules object:
  src/test/protocol/STTx_test.cpp
Labels: Bug, Perf impact not expected

#4789 `PriceOracle`: Price Oracle (XLS-47d)
  Builds/CMake/RippledCore.cmake
  src/ripple/app/tx/impl/DeleteAccount.cpp
  src/ripple/app/tx/impl/DeleteOracle.cpp
  src/ripple/app/tx/impl/DeleteOracle.h
  src/ripple/app/tx/impl/InvariantCheck.cpp
  src/ripple/app/tx/impl/SetOracle.cpp
  src/ripple/app/tx/impl/SetOracle.h
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/protocol/ErrorCodes.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/Indexes.h
  src/ripple/protocol/LedgerFormats.h
  src/ripple/protocol/Protocol.h
  src/ripple/protocol/SField.h
  src/ripple/protocol/STCurrency.h
  src/ripple/protocol/STObject.h
  src/ripple/protocol/TER.h
  src/ripple/protocol/TxFormats.h
  src/ripple/protocol/impl/ErrorCodes.cpp
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/Indexes.cpp
  src/ripple/protocol/impl/InnerObjectFormats.cpp
  src/ripple/protocol/impl/LedgerFormats.cpp
  src/ripple/protocol/impl/SField.cpp
  src/ripple/protocol/impl/STCurrency.cpp
  src/ripple/protocol/impl/STObject.cpp
  src/ripple/protocol/impl/STParsedJSON.cpp
  src/ripple/protocol/impl/STVar.cpp
  src/ripple/protocol/impl/TER.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/GetAggregatePrice.cpp
  src/ripple/rpc/handlers/Handlers.h
  src/ripple/rpc/handlers/LedgerEntry.cpp
  src/ripple/rpc/impl/Handler.cpp
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/test/app/Oracle_test.cpp
  src/test/jtx/Oracle.h
  src/test/jtx/impl/Oracle.cpp
  src/test/rpc/GetAggregatePrice_test.cpp
Labels: API Change, Feature Request, Amendment, Testable, Will Need Documentation, Clio Reviewed, Perf SignedOff
