Repository XRPLF/rippled, pull requests merged in 2024-11, with the labels that each got.

#5142 Add AMMClawback Transaction (XLS-0073d)
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/TxFlags.h
  include/xrpl/protocol/detail/features.macro
  include/xrpl/protocol/detail/transactions.macro
  include/xrpl/protocol/jss.h
  src/libxrpl/protocol/TER.cpp
  src/test/app/AMMClawback_test.cpp
  src/test/app/AMM_test.cpp
  src/test/app/MPToken_test.cpp
  src/test/jtx/AMM.h
  src/test/jtx/impl/AMM.cpp
  src/test/rpc/Status_test.cpp
  src/xrpld/app/tx/detail/AMMClawback.cpp
  src/xrpld/app/tx/detail/AMMClawback.h
  src/xrpld/app/tx/detail/AMMCreate.cpp
  src/xrpld/app/tx/detail/AMMDeposit.cpp
  src/xrpld/app/tx/detail/AMMWithdraw.cpp
  src/xrpld/app/tx/detail/AMMWithdraw.h
  src/xrpld/app/tx/detail/InvariantCheck.cpp
  src/xrpld/app/tx/detail/applySteps.cpp
Labels: Passed

#5179 Fix unity build
  src/test/app/MPToken_test.cpp
Labels: Build System

#5176 Add fixAMMv1_2 amendment
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/detail/features.macro
  src/test/app/AMM_test.cpp
  src/xrpld/app/paths/detail/AMMLiquidity.cpp
  src/xrpld/app/tx/detail/AMMClawback.cpp
  src/xrpld/app/tx/detail/AMMWithdraw.cpp
  src/xrpld/app/tx/detail/AMMWithdraw.h
Labels: Passed

#5172 Fix tokens comparison in Payment for temREDUNDANT error
  include/xrpl/protocol/Asset.h
  src/libxrpl/protocol/Asset.cpp
  src/test/app/MPToken_test.cpp
  src/xrpld/app/tx/detail/Payment.cpp
Labels: Passed

#5124 Fix deadlock in InboundLedgers and NetworkOPs
  include/xrpl/basics/scope.h
  src/xrpld/app/ledger/detail/InboundLedgers.cpp
  src/xrpld/app/ledger/detail/LedgerMaster.cpp
  src/xrpld/app/misc/NetworkOPs.cpp
Labels: Passed

#5177 Bug: Replace Uint192 with Hash192 in server_definitions response
  src/test/rpc/ServerInfo_test.cpp
  src/xrpld/rpc/handlers/ServerInfo.cpp
Labels: Passed, Blocked

#5189 Fix ledger_entry crash on invalid request
  src/test/rpc/LedgerRPC_test.cpp
  src/xrpld/rpc/handlers/LedgerEntry.cpp
Labels: Passed, Bug, Perf impact not expected

#5190 fix: include `index` in `server_definitions` RPC
  src/libxrpl/protocol/SField.cpp
  src/test/rpc/ServerInfo_test.cpp
Labels: Passed, Perf impact not expected
