Repository XRPLF/rippled, pull requests merged in 2024-01, with the labels that each got.

#4848 Websocket should only call async_close once
  src/ripple/server/impl/BaseWSPeer.h
Labels: Passed, Bug, Dependencies, Perf impact not expected

#4822 Improve lifetime management of ledger objects (`SLE`s) to prevent runaway memory usage. AKA "Is it caching? It's always caching."
  src/ripple/app/ledger/InboundLedgers.h
  src/ripple/app/ledger/LedgerReplayer.h
  src/ripple/app/ledger/impl/InboundLedgers.cpp
  src/ripple/app/ledger/impl/LedgerMaster.cpp
  src/ripple/app/main/Application.cpp
  src/ripple/app/paths/PathRequests.cpp
  src/ripple/consensus/Validations.h
  src/ripple/ledger/CachedView.h
  src/ripple/ledger/impl/CachedView.cpp
  src/ripple/net/InfoSub.h
  src/ripple/protocol/STAccount.h
  src/ripple/protocol/STBitString.h
  src/ripple/protocol/STBlob.h
  src/ripple/protocol/STInteger.h
  src/ripple/protocol/STIssue.h
  src/ripple/protocol/STVector256.h
  src/ripple/protocol/STXChainBridge.h
  src/test/app/LedgerReplay_test.cpp
  src/test/jtx/Env.h
Labels: Passed, Bug, Perf Attn Needed

#4747 clang warning about deprecated sprintf usage
  src/ripple/json/impl/json_reader.cpp
Labels: Passed, Perf impact not expected

#4826 Add DeliverMax to more JSONRPC tests
  src/test/rpc/JSONRPC_test.cpp
Labels: Passed, Perf impact not expected

#4875 PR Template - add Type of Change: `Performance`
  .github/pull_request_template.md
Labels: Perf impact not expected

#4882 Revert "Asynchronously write batches to NuDB. (#4503)"
  src/ripple/nodestore/Types.h
  src/ripple/nodestore/backend/NuDBFactory.cpp
Labels: Perf SignedOff

#4846 Update help message about unit test-suite pattern matching
  CONTRIBUTING.md
  src/ripple/app/main/Main.cpp
  src/test/app/NFTokenBurn_test.cpp
  src/test/app/NFToken_test.cpp
  src/test/app/Offer_test.cpp
  src/test/app/TxQ_test.cpp
Labels: Passed, Documentation

#4849 Improve coverage reporting
  .codecov.yml
  .github/actions/build/action.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
  BUILD.md
  Builds/CMake/CodeCoverage.cmake
  Builds/CMake/RippledCov.cmake
  Builds/CMake/RippledInterface.cmake
  Builds/CMake/RippledSanity.cmake
  Builds/CMake/RippledSettings.cmake
  CMakeLists.txt
  bin/ci/ubuntu/build-and-test.sh
Labels: Perf impact not expected
