Repository XRPLF/rippled, pull requests merged in 2024-06, with the labels that each got.

#5001 Fix compatibility with Conan 2.x
  BUILD.md
  conanfile.py
Labels: Passed

#5032 Amendment fixReducedOffersV2 fixes issue #4937
  src/ripple/app/paths/AMMOffer.h
  src/ripple/app/paths/impl/AMMOffer.cpp
  src/ripple/app/paths/impl/BookStep.cpp
  src/ripple/app/tx/impl/Offer.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/Quality.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/Quality.cpp
  src/test/app/AMM_test.cpp
  src/test/app/Flow_test.cpp
  src/test/app/Offer_test.cpp
  src/test/app/ReducedOffer_test.cpp
Labels: Passed, Bug, Amendment

#4845 XLS-52d: NFTokenMintOffer
  src/ripple/app/tx/impl/NFTokenCreateOffer.cpp
  src/ripple/app/tx/impl/NFTokenMint.cpp
  src/ripple/app/tx/impl/details/NFTokenUtils.cpp
  src/ripple/app/tx/impl/details/NFTokenUtils.h
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/NFTokenOfferID.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/test/app/NFToken_test.cpp
  src/test/jtx/impl/token.cpp
  src/test/jtx/token.h
Labels: Passed

#4521 docs: explain how to find a clang-format patch generated by CI
  CONTRIBUTING.md
Labels: Documentation, Trivial

#4509 Update codebase from boost::string_view into std::string_view
  BUILD.md
  src/ripple/app/misc/ValidatorList.h
  src/ripple/app/misc/impl/ValidatorList.cpp
  src/ripple/basics/StringUtilities.h
  src/ripple/basics/base64.h
  src/ripple/basics/impl/StringUtilities.cpp
  src/ripple/basics/impl/base64.cpp
  src/ripple/beast/core/LexicalCast.h
  src/ripple/json/Output.h
  src/ripple/overlay/impl/Cluster.cpp
  src/ripple/overlay/impl/Handshake.cpp
  src/ripple/overlay/impl/OverlayImpl.cpp
  src/ripple/overlay/impl/PeerImp.cpp
  src/ripple/resource/ResourceManager.h
  src/ripple/resource/impl/ResourceManager.cpp
  src/ripple/rpc/Context.h
  src/ripple/rpc/Role.h
  src/ripple/rpc/ServerHandler.h
  src/ripple/rpc/handlers/Ping.cpp
  src/ripple/rpc/impl/Role.cpp
  src/ripple/rpc/impl/ServerHandler.cpp
  src/ripple/rpc/impl/WSInfoSub.h
  src/test/app/NFTokenDir_test.cpp
  src/test/jtx/TrustedPublisherServer.h
Labels: Tech Debt

#4946 Add the fixEnforceNFTokenTrustline amendment:
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/NFToken_test.cpp
  src/test/app/Offer_test.cpp
Labels: Passed, Amendment, Perf impact not expected

#4924 Change order of checks in amm_info
  src/ripple/rpc/handlers/AMMInfo.cpp
  src/test/jtx/AMM.h
  src/test/jtx/impl/AMM.cpp
  src/test/rpc/AMMInfo_test.cpp
Labels: Clio Reviewed, APIv3

#5047 fixInnerObjTemplate2 amendment
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/STObject.h
  src/libxrpl/protocol/Feature.cpp
  src/libxrpl/protocol/STObject.cpp
  src/libxrpl/protocol/XChainAttestations.cpp
  src/test/rpc/LedgerData_test.cpp
  src/xrpld/app/ledger/Ledger.cpp
  src/xrpld/app/misc/detail/AMMUtils.cpp
  src/xrpld/app/tx/detail/AMMVote.cpp
  src/xrpld/app/tx/detail/Change.cpp
  src/xrpld/app/tx/detail/SetSignerList.cpp
  src/xrpld/rpc/detail/TransactionSign.cpp
Labels: Passed, Bug, Amendment, Perf impact not expected
