Repository XRPLF/rippled, pull requests merged in 2024-10, with the labels that each got.

#5064 docs: clean up API-CHANGELOG.md
  API-CHANGELOG.md
Labels: Documentation, Trivial

#4959 Elaborate Error Message for rpcInternal
  src/xrpld/net/detail/RPCCall.cpp
Labels: Passed

#5122 Consolidate definitions of fields, objects, transactions, and features
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/LedgerFormats.h
  include/xrpl/protocol/SField.h
  include/xrpl/protocol/TxFormats.h
  include/xrpl/protocol/detail/features.macro
  include/xrpl/protocol/detail/ledger_entries.macro
  include/xrpl/protocol/detail/sfields.macro
  include/xrpl/protocol/detail/transactions.macro
  include/xrpl/protocol/jss.h
  src/libxrpl/protocol/Feature.cpp
  src/libxrpl/protocol/LedgerFormats.cpp
  src/libxrpl/protocol/SField.cpp
  src/libxrpl/protocol/TxFormats.cpp
  src/test/jtx/impl/AMM.cpp
  src/xrpld/app/tx/detail/CancelCheck.h
  src/xrpld/app/tx/detail/CancelOffer.h
  src/xrpld/app/tx/detail/CashCheck.h
  src/xrpld/app/tx/detail/Change.h
  src/xrpld/app/tx/detail/CreateCheck.h
  src/xrpld/app/tx/detail/CreateOffer.h
  src/xrpld/app/tx/detail/CreateTicket.h
  src/xrpld/app/tx/detail/DeleteAccount.h
  src/xrpld/app/tx/detail/DeleteOracle.h
  src/xrpld/app/tx/detail/PayChan.h
  src/xrpld/app/tx/detail/SetAccount.h
  src/xrpld/app/tx/detail/SetOracle.h
  src/xrpld/app/tx/detail/SetSignerList.h
  src/xrpld/app/tx/detail/SetTrust.h
  src/xrpld/app/tx/detail/XChainBridge.h
  src/xrpld/app/tx/detail/applySteps.cpp
Labels: Passed

#5154 fixes small typos in RELEASENOTES.md
  RELEASENOTES.md
Labels: Passed, Trivial

#5046 fix account_objects with invalid marker do not return an error
  src/test/rpc/AccountObjects_test.cpp
  src/xrpld/rpc/detail/RPCHelpers.cpp
  src/xrpld/rpc/handlers/AccountObjects.cpp
Labels: Passed

#5156 protobuf dependencies are missing on the clean machine
  docs/build/environment.md
Labels: Passed, Trivial

#5169 Add hubs.xrpkuwait.com to bootstrap
  cfg/rippled-example.cfg
  src/xrpld/overlay/detail/OverlayImpl.cpp
Labels: Passed
