Repository XRPLF/rippled, pull requests merged in 2024-09, with the labels that each got.

#5120 Retry RPC commands to try to fix MacOS CI jobs
  src/test/jtx/impl/Env.cpp
  src/xrpld/app/misc/NetworkOPs.cpp
Labels: Passed, CI, Perf impact not expected

#5096 updates to book_changes RPC command
  API-CHANGELOG.md
  src/test/rpc/BookChanges_test.cpp
  src/xrpld/rpc/BookChanges.h
  src/xrpld/rpc/handlers/BookOffers.cpp
Labels: Passed

#5140 Fix order of SQLite PRAGMAS to allow configurable page_size
  src/xrpld/core/DatabaseCon.h
Labels: Bug, Trivial

#5135 SQLite: Allow configurable sqlite database pragma variables.
  cfg/rippled-example.cfg
  src/test/nodestore/Database_test.cpp
  src/xrpld/app/main/DBInit.h
  src/xrpld/app/rdb/backend/detail/Node.cpp
  src/xrpld/app/rdb/detail/Vacuum.cpp
  src/xrpld/app/rdb/detail/Wallet.cpp
  src/xrpld/core/DatabaseCon.h
  src/xrpld/core/detail/DatabaseCon.cpp
Labels: Passed
