Repository XRPLF/rippled, pull requests merged in 2024-04, with the labels that each got.

#4751 amendment fix to add `sfPreviousTxnID`/`sfPreviousTxnLgrSequence` to all ledger objects
  src/ripple/ledger/impl/ApplyStateTable.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/STLedgerEntry.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/LedgerFormats.cpp
  src/ripple/protocol/impl/STLedgerEntry.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/impl/RPCHelpers.cpp
  src/test/app/AMMExtended_test.cpp
  src/test/app/TxQ_test.cpp
  src/test/ledger/Directory_test.cpp
  src/test/rpc/TransactionEntry_test.cpp
Labels: Passed, Amendment

#4986 Unit tests for AMM offer overflow fix
  src/test/app/AMM_test.cpp
Labels: Passed, Perf impact not expected

#4977 Codecov coverage reporting fixes
  .codecov.yml
  .github/workflows/nix.yml
  Builds/CMake/CodeCoverage.cmake
Labels: Passed

#4971 Increase test coverage
  src/ripple/app/misc/impl/AMMUtils.cpp
  src/ripple/app/paths/AMMOffer.h
  src/ripple/app/paths/impl/AMMOffer.cpp
  src/ripple/app/tx/impl/AMMDeposit.cpp
  src/ripple/app/tx/impl/AMMWithdraw.cpp
  src/ripple/protocol/STIssue.h
  src/ripple/protocol/impl/STIssue.cpp
  src/test/app/AMMExtended_test.cpp
  src/test/app/AMM_test.cpp
  src/test/jtx/AMM.h
  src/test/jtx/Env.h
  src/test/jtx/impl/AMM.cpp
  src/test/jtx/impl/Env.cpp
  src/test/jtx/multisign.h
  src/test/rpc/AMMInfo_test.cpp
Labels: Passed

#4982 AMM Unit tests: rounding down of equal asset deposit LPToken calculation
  src/test/app/AMM_test.cpp
Labels: Passed

#4989 fix: resolve database deadlock:
  src/ripple/nodestore/impl/DatabaseRotatingImp.h
Labels: Passed

#4987 Add RPC error checking support to unit tests
  src/test/app/MultiSign_test.cpp
  src/test/app/Regression_test.cpp
  src/test/app/TxQ_test.cpp
  src/test/jtx.h
  src/test/jtx/Env.h
  src/test/jtx/Env_test.cpp
  src/test/jtx/JTx.h
  src/test/jtx/impl/Env.cpp
  src/test/jtx/rpc.h
  src/test/protocol/Memo_test.cpp
Labels: Passed, Perf impact not expected

#4958 [TRIVIAL] chore: fix typos in comments
  src/ripple/app/misc/TxQ.h
  src/ripple/app/paths/impl/Steps.h
  src/ripple/app/reporting/ETLSource.cpp
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
Labels: Passed

#4984 Update list of maintainers:
  CONTRIBUTING.md
Labels: Passed, Blocked
