Repository XRPLF/rippled, pull requests merged in 2024-12, with the labels that each got.

#5174 test: Add more test cases for Base58 parser
  include/xrpl/protocol/detail/b58_utils.h
  src/test/protocol/types_test.cpp
Labels: Passed, Tech Debt, Perf impact not expected, Blocked

#5199 refactor: clean up `LedgerEntry.cpp`
  API-CHANGELOG.md
  src/test/rpc/LedgerRPC_test.cpp
  src/xrpld/net/detail/RPCCall.cpp
  src/xrpld/rpc/detail/RPCHelpers.cpp
  src/xrpld/rpc/handlers/LedgerEntry.cpp
Labels: Passed, Added to API Changelog

#5200 Add MPTIssue to STIssue
  include/xrpl/protocol/Asset.h
  include/xrpl/protocol/Indexes.h
  include/xrpl/protocol/Issue.h
  include/xrpl/protocol/MPTIssue.h
  include/xrpl/protocol/SOTemplate.h
  include/xrpl/protocol/STAmount.h
  include/xrpl/protocol/STIssue.h
  include/xrpl/protocol/STXChainBridge.h
  src/libxrpl/protocol/Indexes.cpp
  src/libxrpl/protocol/STIssue.cpp
  src/libxrpl/protocol/STTx.cpp
  src/test/app/MPToken_test.cpp
  src/test/protocol/STIssue_test.cpp
  src/xrpld/app/ledger/OrderBookDB.cpp
  src/xrpld/app/misc/detail/AMMUtils.cpp
  src/xrpld/app/tx/detail/AMMBid.cpp
  src/xrpld/app/tx/detail/AMMClawback.cpp
  src/xrpld/app/tx/detail/AMMDelete.cpp
  src/xrpld/app/tx/detail/AMMDeposit.cpp
  src/xrpld/app/tx/detail/AMMVote.cpp
  src/xrpld/app/tx/detail/AMMWithdraw.cpp
  src/xrpld/rpc/handlers/AMMInfo.cpp
Labels: Passed

#5218 fix: allow overlapping types in `Expected`
  include/xrpl/basics/Expected.h
  src/test/basics/Expected_test.cpp
Labels: Passed

#5197 [TRIVIAL] Fix Add header for set_difference
  src/test/csf/Tx.h
Labels: Passed, Trivial
