Repository XRPLF/rippled, pull requests merged in 2024-07, with the labels that each got.

#5045 fix "account_nfts" with unassociated marker returning issue
  src/test/rpc/AccountObjects_test.cpp
  src/xrpld/app/tx/detail/NFTokenMint.h
  src/xrpld/rpc/handlers/AccountObjects.cpp
Labels: Passed

#5055 [TRIVIAL] Bump codecov plugin version to version 4.5.0
  .github/workflows/nix.yml
Labels: Passed

#4663 Invariant: prevent a deleted account from leaving (most) artifacts on the ledger.
  cmake/RippledCore.cmake
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/Indexes.h
  src/libxrpl/protocol/Feature.cpp
  src/test/ledger/Invariants_test.cpp
  src/xrpld/app/misc/FeeVoteImpl.cpp
  src/xrpld/app/tx/detail/InvariantCheck.cpp
  src/xrpld/app/tx/detail/InvariantCheck.h
  src/xrpld/app/tx/detail/NFTokenUtils.cpp
Labels: Passed, Amendment, Perf SignedOff

#5049 fix CTID in tx command returns invalidParams on lowercase hex
  src/test/rpc/Transaction_test.cpp
  src/xrpld/rpc/CTID.h
Labels: Passed

#5053 chore: remove repeat words
  external/secp256k1/src/secp256k1.c
  src/test/csf/CollectorRef.h
  src/test/csf/Digraph.h
  src/xrpld/shamap/detail/TaggedPointer.h
  src/xrpld/shamap/detail/TaggedPointer.ipp
Labels: Passed

#5052 Add xrpld build option and Conan package test
  .github/actions/build/action.yml
  .github/actions/dependencies/action.yml
  .github/workflows/nix.yml
  cmake/RippledCore.cmake
  cmake/RippledInstall.cmake
  cmake/RippledSettings.cmake
  conanfile.py
  examples/example/CMakeLists.txt
  examples/example/conanfile.py
  examples/example/src/example.cpp
Labels: Passed

#5067 Update BUILD.md after PR 5052
  BUILD.md
Labels: Passed, Documentation, Perf impact not expected

#5058 chore: Rename two files from Directory* to Dir*:
  src/test/app/Escrow_test.cpp
  src/test/app/PayChan_test.cpp
  src/test/ledger/Directory_test.cpp
  src/xrpld/app/paths/detail/BookStep.cpp
  src/xrpld/app/tx/detail/NFTokenBurn.cpp
  src/xrpld/app/tx/detail/NFTokenUtils.cpp
  src/xrpld/ledger/Dir.h
  src/xrpld/ledger/detail/Dir.cpp
Labels: Passed, Tech Debt, Trivial, Perf impact not expected

#5059 chore: Add comments to SignerEntries.h
  src/xrpld/app/tx/detail/SignerEntries.cpp
  src/xrpld/app/tx/detail/SignerEntries.h
Labels: Passed, Tech Debt, Trivial, Perf impact not expected

#5056 fix account_objects to disallow filtering by types that an account ca…
  src/test/rpc/AccountObjects_test.cpp
  src/xrpld/rpc/detail/RPCHelpers.cpp
  src/xrpld/rpc/detail/RPCHelpers.h
  src/xrpld/rpc/handlers/AccountObjects.cpp
Labels: Passed

#5061 [TRIVIAL] Fix NuDB build error
  BUILD.md
  external/nudb/conandata.yml
  external/nudb/conanfile.py
  external/nudb/patches/2.0.8-0001-add-include-stdexcept-for-msvc.patch
Labels: Passed, Build System, Bug, Trivial, Perf impact not expected, High Impact

#5072 [TRIVIAL] Ensure all sorting is ASCII-order consistently across platforms
  Builds/levelization/levelization.sh
Labels: Passed, Trivial

#5063 fix: change error for invalid `feature` param in `feature` RPC
  src/test/rpc/Feature_test.cpp
  src/xrpld/rpc/handlers/Feature1.cpp
Labels: Passed

#4856 [Trivial] Remove unused constants from resource/Fees.h
  include/xrpl/resource/Fees.h
Labels: Passed, Low Priority

#5010 docs: Document the process for merging pull requests
  CONTRIBUTING.md
Labels: Passed
