Repository XRPLF/rippled, pull requests merged in 2024-08, with the labels that each got.

#5071 Fix crash inside `OverlayImpl` loops over `ids_`
  src/test/overlay/tx_reduce_relay_test.cpp
  src/xrpld/overlay/detail/OverlayImpl.cpp
Labels: Passed

#5084 chore: Update gcovr EXCLUDE
  cmake/RippledCov.cmake
Labels: Passed, Trivial

#5087 refactor: Factor out Transactor::trapTransaction
  src/xrpld/app/tx/detail/Transactor.cpp
  src/xrpld/app/tx/detail/Transactor.h
Labels: Passed, Trivial

#4945 Address rare corruption of NFTokenPage linked list
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/SField.h
  include/xrpl/protocol/TER.h
  include/xrpl/protocol/TxFormats.h
  include/xrpl/protocol/jss.h
  src/libxrpl/protocol/Feature.cpp
  src/libxrpl/protocol/SField.cpp
  src/libxrpl/protocol/TER.cpp
  src/libxrpl/protocol/TxFormats.cpp
  src/test/app/FixNFTokenPageLinks_test.cpp
  src/test/app/NFTokenBurn_test.cpp
  src/test/jtx.h
  src/test/jtx/impl/ledgerStateFix.cpp
  src/test/jtx/ledgerStateFix.h
  src/test/ledger/Invariants_test.cpp
  src/xrpld/app/tx/detail/InvariantCheck.cpp
  src/xrpld/app/tx/detail/InvariantCheck.h
  src/xrpld/app/tx/detail/LedgerStateFix.cpp
  src/xrpld/app/tx/detail/LedgerStateFix.h
  src/xrpld/app/tx/detail/NFTokenUtils.cpp
  src/xrpld/app/tx/detail/NFTokenUtils.h
  src/xrpld/app/tx/detail/applySteps.cpp
Labels: Passed, Amendment, Perf impact not expected

#5091 chore: Fix documentation generation job:
  .github/workflows/doxygen.yml
  bin/ci/README.md
  cmake/RippledDocs.cmake
  docs/Doxyfile
  external/README.md
  include/xrpl/proto/org/xrpl/rpc/v1/README.md
  src/xrpld/app/reporting/README.md
Labels: Passed, Documentation, Perf impact not expected

#5081 Remove dead headers
  bin/ci/README.md
  bin/ci/build.sh
  bin/ci/test.sh
  bin/ci/ubuntu/build-and-test.sh
  bin/ci/ubuntu/build-in-docker.sh
  bin/ci/ubuntu/travis-cache-start.sh
  include/xrpl/beast/test/fail_counter.h
  include/xrpl/beast/test/fail_stream.h
  include/xrpl/beast/test/pipe_stream.h
  include/xrpl/beast/test/sig_wait.h
  include/xrpl/beast/test/string_iostream.h
  include/xrpl/beast/test/string_istream.h
  include/xrpl/beast/test/string_ostream.h
  include/xrpl/beast/test/test_allocator.h
  include/xrpl/beast/unit_test/dstream.h
  include/xrpl/beast/utility/hash_pair.h
  src/xrpld/peerfinder/detail/Logic.h
  src/xrpld/peerfinder/detail/Reporting.h
  src/xrpld/peerfinder/sim/FunctionQueue.h
  src/xrpld/peerfinder/sim/GraphAlgorithms.h
  src/xrpld/peerfinder/sim/Message.h
  src/xrpld/peerfinder/sim/NodeSnapshot.h
  src/xrpld/peerfinder/sim/Params.h
  src/xrpld/peerfinder/sim/Predicates.h
Labels: Passed, Trivial, Remove unused code

#5083 Update options documentation
  BUILD.md
Labels: Passed
