Repository XRPLF/rippled, pull requests merged in 2025-06, with the labels that each got.

#5347 TRIVIAL: Collapse some split log messages into one
  src/xrpld/app/ledger/detail/InboundLedger.cpp
Labels: Low Priority, Trivial

#5479 fix: improve multisign usage of `simulate`
  src/test/rpc/Simulate_test.cpp
  src/xrpld/app/tx/detail/Transactor.cpp
Labels: Ready to merge

#5455 Change getNodeFat Missing Node State Tree error into warning
  src/xrpld/overlay/detail/PeerImp.cpp
Labels: Trivial
