Repository XRPLF/rippled, pull requests merged in 2025-10, with the labels that each got.

#5832 Merge 2.6.1 into develop
  include/xrpl/protocol/detail/features.macro
  src/libxrpl/protocol/BuildInfo.cpp
Labels: Trivial

#5823 Pre-emptive FD/handle guarding + exponential backoff
  include/xrpl/server/detail/Door.h
Labels: Ready to merge

#5829 fix: Transaction sig checking functions do not get a full context
  src/xrpld/app/tx/detail/Transactor.cpp
  src/xrpld/app/tx/detail/Transactor.h
Labels: Ready to merge, Bug

#5849 Move Smart Escrow tests to separate file
  src/test/app/EscrowSmart_test.cpp
  src/test/app/Escrow_test.cpp
Labels: Trivial

#5856 Update CI strategy matrix to use new RHEL 9 and RHEL 10 images
  .github/scripts/strategy-matrix/generate.py
  .github/scripts/strategy-matrix/linux.json
  .github/scripts/strategy-matrix/macos.json
  .github/scripts/strategy-matrix/windows.json
  .github/workflows/reusable-build-test.yml
  .github/workflows/upload-conan-deps.yml
Labels: Ready to merge, Trivial

#5827 Additional tests for Simulate metadata
  src/test/rpc/Simulate_test.cpp
Labels: Ready to merge

#5518 Add vault invariants
  include/xrpl/protocol/detail/transactions.macro
  src/test/app/Invariants_test.cpp
  src/test/app/Vault_test.cpp
  src/xrpld/app/tx/detail/InvariantCheck.cpp
  src/xrpld/app/tx/detail/InvariantCheck.h
  src/xrpld/app/tx/detail/VaultDeposit.cpp
  src/xrpld/app/tx/detail/VaultSet.cpp
Labels: Ready to merge
