Repository XRPLF/rippled, pull requests merged in 2025-05, with the labels that each got.

#4985 Improve transaction relay logic
  src/test/app/HashRouter_test.cpp
  src/xrpld/app/ledger/LocalTxs.h
  src/xrpld/app/ledger/detail/LedgerMaster.cpp
  src/xrpld/app/ledger/detail/LocalTxs.cpp
  src/xrpld/app/main/Application.cpp
  src/xrpld/app/main/Tuning.h
  src/xrpld/app/misc/CanonicalTXSet.cpp
  src/xrpld/app/misc/HashRouter.cpp
  src/xrpld/app/misc/HashRouter.h
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/app/misc/NetworkOPs.h
  src/xrpld/app/misc/Transaction.h
Labels: Ready to merge, Perf Test Desired (Optional)

#5426 Ensure that coverage file generation is atomic.
  .github/workflows/nix.yml
  cmake/CodeCoverage.cmake
Labels: Ready to merge, Trivial

#5443 Fix GCC-15
  include/xrpl/beast/hash/uhash.h
  include/xrpl/beast/net/IPEndpoint.h
  include/xrpl/protocol/AccountID.h
  include/xrpl/protocol/Book.h
  include/xrpl/protocol/UintTypes.h
  include/xrpl/resource/detail/Key.h
  src/xrpld/app/paths/RippleLineCache.h
Labels: Trivial

#5428 Add codecov badge, raised .codecov.yml thresholds
  .codecov.yml
  README.md
Labels: Ready to merge, Trivial

#5447 Fix pseudo-account ID calculation
  src/xrpld/ledger/detail/View.cpp
Labels: Ready to merge, Bug

#5288 docs(BUILD): add -j $(nproc)
  BUILD.md
Labels: Ready to merge, Trivial

#5452 Fix handling of expired credentials in `VaultDeposit`
  src/test/app/Vault_test.cpp
  src/xrpld/app/misc/CredentialHelpers.cpp
  src/xrpld/ledger/detail/View.cpp
Labels: Ready to merge, Bug

#5459 Fix unity build error
  src/test/app/Vault_test.cpp
Labels: Ready to merge, Bug
