Repository XRPLF/rippled, pull requests merged in 2025-04, with the labels that each got.

#5377 Fix undefined uint128_t type on Windows non-unity builds
  src/libxrpl/basics/Number.cpp
Labels: Trivial

#5386 fix: uint128 ambiguousness breaking macos unity build
  src/libxrpl/basics/mulDiv.cpp
Labels: Ready to merge, Trivial

#5381 Fix to correct memory ordering for compare_exchange_weak and wait in the intrusive reference counting logic
  include/xrpl/basics/IntrusiveRefCounts.h
Labels: Ready to merge

#5385 fix: disable `channel_authorize` when `signing_support` is disabled
  API-CHANGELOG.md
  src/xrpld/rpc/handlers/PayChanClaim.cpp
Labels: Ready to merge

#5390 fix: Use the build image from ghcr.io
  .github/workflows/doxygen.yml
  .github/workflows/libxrpl.yml
  .github/workflows/nix.yml
Labels: Ready to merge, Trivial

#5387 Remove UNREACHABLE from `NetworkOPsImp::processTrustedProposal`
  src/xrpld/app/misc/NetworkOPs.cpp
Labels: Ready to merge, Found with Antithesis

#5348 Instrument proposal, validation and transaction messages
  src/test/overlay/traffic_count_test.cpp
  src/xrpld/overlay/Message.h
  src/xrpld/overlay/detail/Message.cpp
  src/xrpld/overlay/detail/OverlayImpl.cpp
  src/xrpld/overlay/detail/OverlayImpl.h
  src/xrpld/overlay/detail/PeerImp.cpp
  src/xrpld/overlay/detail/TrafficCount.cpp
  src/xrpld/overlay/detail/TrafficCount.h
Labels: Ready to merge

#5376 refactor(trivial): reorganize ledger entry tests and helper functions
  src/test/rpc/LedgerEntry_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
  src/xrpld/rpc/handlers/LedgerEntry.cpp
Labels: Trivial

#4717 fixPayChanV1
  include/xrpl/protocol/detail/features.macro
  src/test/app/PayChan_test.cpp
  src/xrpld/app/tx/detail/Escrow.cpp
  src/xrpld/app/tx/detail/PayChan.cpp
  src/xrpld/ledger/View.h
  src/xrpld/ledger/detail/View.cpp
Labels: Tx Change, API Change, Amendment, Testable, Will Need Documentation, Perf impact not expected

#4738 Patch CTID
  src/libxrpl/protocol/ErrorCodes.cpp
  src/test/rpc/Transaction_test.cpp
  src/xrpld/app/ledger/TransactionMaster.h
  src/xrpld/app/ledger/detail/TransactionMaster.cpp
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/app/misc/Transaction.h
  src/xrpld/app/misc/detail/AccountTxPaging.cpp
  src/xrpld/app/misc/detail/Transaction.cpp
  src/xrpld/app/rdb/backend/detail/Node.cpp
  src/xrpld/rpc/CTID.h
  src/xrpld/rpc/handlers/Tx.cpp
Labels: API Change, Testable, Clio Reviewed, Perf Attn Needed

#5396 Clean up test logging to make it easier to search
  src/test/app/AMM_test.cpp
  src/test/app/DepositAuth_test.cpp
  src/test/jtx/Env.h
  src/test/jtx/impl/creds.cpp
  src/test/jtx/impl/dids.cpp
  src/test/jtx/impl/ledgerStateFixes.cpp
  src/test/rpc/DepositAuthorized_test.cpp
  src/test/unit_test/multi_runner.cpp
  src/xrpld/rpc/handlers/DoManifest.cpp
Labels: Ready to merge

#5400 chore: Run CI jobs on PRs that are ready or have the "DraftRunCI" label
  .github/workflows/clang-format.yml
  .github/workflows/levelization.yml
  .github/workflows/libxrpl.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: Ready to merge, CI, Trivial

#5365 Replace random endpoint resolution with sequential
  src/xrpld/app/misc/detail/ValidatorSite.cpp
  src/xrpld/app/misc/detail/WorkBase.h
Labels: Trivial
