Repository XRPLF/rippled, pull requests merged in 2025-02, with the labels that each got.

#5225 Improve git commit hash lookup
  CMakeLists.txt
  include/xrpl/protocol/jss.h
  src/test/rpc/ServerInfo_test.cpp
  src/xrpld/app/main/Main.cpp
  src/xrpld/app/misc/NetworkOPs.cpp
Labels: Ready to merge, API Change, Build System, Bug, Tech Debt, Documentation, Perf impact not expected

#5227 Amendment `fixFrozenLPTokenTransfer`: Prohibit transfer of LPToken when an asset is frozen
  .github/actions/dependencies/action.yml
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/detail/features.macro
  src/test/app/LPTokenTransfer_test.cpp
  src/xrpld/app/misc/detail/AMMUtils.cpp
  src/xrpld/app/paths/detail/DirectStep.cpp
  src/xrpld/app/paths/detail/StepChecks.h
  src/xrpld/ledger/View.h
  src/xrpld/ledger/detail/View.cpp
Labels: Ready to merge, Bug, Amendment

#5256 Updates Conan dependencies
  conanfile.py
  external/rocksdb/conanfile.py
  external/soci/conanfile.py
Labels: Ready to merge

#5265 fix issues in `simulate` RPC
  API-CHANGELOG.md
  src/test/jtx/JTx.h
  src/test/jtx/impl/Env.cpp
  src/test/rpc/JSONRPC_test.cpp
  src/test/rpc/Simulate_test.cpp
  src/xrpld/rpc/detail/TransactionSign.cpp
  src/xrpld/rpc/handlers/Simulate.cpp
Labels: Ready to merge

#5275 Do not allow creating PDs if credentials are not enabled
  src/test/app/PermissionedDomains_test.cpp
  src/xrpld/app/tx/detail/PermissionedDomainSet.cpp
Labels: Ready to merge

#5250 fix amendment: flag check for credentials
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/detail/features.macro
  src/test/app/Credentials_test.cpp
  src/test/app/MultiSign_test.cpp
  src/xrpld/app/tx/detail/Credentials.cpp
  src/xrpld/app/tx/detail/SetSignerList.cpp
Labels: Ready to merge, Bug, Tech Debt, Amendment

#5283 docs: Add a summary of the git commit message rules
  CONTRIBUTING.md
Labels: Ready to merge, Documentation, Trivial

#5268 chore: Rename missing-commits job, and combine nix job files
  .github/workflows/instrumentation.yml
  .github/workflows/missing-commits.yml
  .github/workflows/nix.yml
Labels: Ready to merge, CI, Trivial

#5279 Fix small typos
  include/xrpl/protocol/AccountID.h
  include/xrpl/protocol/Sign.h
  include/xrpl/protocol/TxFormats.h
  src/xrpld/app/main/Main.cpp
Labels: Ready to merge, Trivial

#5274 BUILD.md: ensure build_type and CMAKE_BUILD_TYPE match
  BUILD.md
Labels: Ready to merge, Documentation

#5269 Replace charge() by fee_.update() in OnMessage functions
  include/xrpl/resource/Charge.h
  src/libxrpl/resource/Charge.cpp
  src/xrpld/overlay/detail/PeerImp.cpp
Labels: Ready to merge

#5276 refactor: Change recursive_mutex to mutex in DatabaseRotatingImp
  Builds/levelization/results/ordering.txt
  src/test/app/SHAMapStore_test.cpp
  src/xrpld/app/misc/SHAMapStoreImp.cpp
  src/xrpld/nodestore/DatabaseRotating.h
  src/xrpld/nodestore/detail/DatabaseRotatingImp.cpp
  src/xrpld/nodestore/detail/DatabaseRotatingImp.h
Labels: Ready to merge

#5271 Support canonical ledger entry names
  API-CHANGELOG.md
  src/test/rpc/RPCHelpers_test.cpp
  src/xrpld/rpc/detail/RPCHelpers.cpp
Labels: Ready to merge

#5126 Reduce duplicate peer traffic for ledger data
  Builds/levelization/results/loops.txt
  include/xrpl/basics/CanProcess.h
  include/xrpl/basics/base_uint.h
  include/xrpl/proto/ripple.proto
  include/xrpl/protocol/LedgerHeader.h
  src/test/app/HashRouter_test.cpp
  src/test/app/LedgerReplay_test.cpp
  src/test/basics/base_uint_test.cpp
  src/test/overlay/ProtocolVersion_test.cpp
  src/test/overlay/reduce_relay_test.cpp
  src/xrpld/app/consensus/RCLConsensus.cpp
  src/xrpld/app/ledger/InboundLedger.h
  src/xrpld/app/ledger/detail/InboundLedger.cpp
  src/xrpld/app/ledger/detail/InboundLedgers.cpp
  src/xrpld/app/ledger/detail/LedgerMaster.cpp
  src/xrpld/app/ledger/detail/TimeoutCounter.cpp
  src/xrpld/app/ledger/detail/TimeoutCounter.h
  src/xrpld/app/misc/HashRouter.cpp
  src/xrpld/app/misc/HashRouter.h
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/app/misc/NetworkOPs.h
  src/xrpld/overlay/Peer.h
  src/xrpld/overlay/detail/PeerImp.cpp
  src/xrpld/overlay/detail/PeerImp.h
  src/xrpld/overlay/detail/PeerSet.cpp
  src/xrpld/overlay/detail/ProtocolMessage.h
  src/xrpld/overlay/detail/ProtocolVersion.cpp
Labels: Ready to merge, Perf Attn Needed

#5291 Log proposals and validations.
  include/xrpl/protocol/STValidation.h
  src/test/csf/Peer.h
  src/xrpld/app/consensus/RCLCxPeerPos.h
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/consensus/Consensus.h
  src/xrpld/consensus/ConsensusProposal.h
Labels: Ready to merge

#5290 docs: Clarifies default port of hosts
  cfg/rippled-example.cfg
Labels: Ready to merge, Trivial

#5299 docs: Revert peer port to 51235
  cfg/rippled-example.cfg
Labels: Ready to merge, Trivial

#5300 Revert "Reduce duplicate peer traffic for ledger data (#5126)"
  Builds/levelization/results/loops.txt
  include/xrpl/basics/CanProcess.h
  include/xrpl/basics/base_uint.h
  include/xrpl/proto/ripple.proto
  include/xrpl/protocol/LedgerHeader.h
  src/test/app/HashRouter_test.cpp
  src/test/app/LedgerReplay_test.cpp
  src/test/basics/base_uint_test.cpp
  src/test/overlay/ProtocolVersion_test.cpp
  src/test/overlay/reduce_relay_test.cpp
  src/xrpld/app/consensus/RCLConsensus.cpp
  src/xrpld/app/ledger/InboundLedger.h
  src/xrpld/app/ledger/detail/InboundLedger.cpp
  src/xrpld/app/ledger/detail/InboundLedgers.cpp
  src/xrpld/app/ledger/detail/LedgerMaster.cpp
  src/xrpld/app/ledger/detail/TimeoutCounter.cpp
  src/xrpld/app/ledger/detail/TimeoutCounter.h
  src/xrpld/app/misc/HashRouter.cpp
  src/xrpld/app/misc/HashRouter.h
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/app/misc/NetworkOPs.h
  src/xrpld/overlay/Peer.h
  src/xrpld/overlay/detail/PeerImp.cpp
  src/xrpld/overlay/detail/PeerImp.h
  src/xrpld/overlay/detail/PeerSet.cpp
  src/xrpld/overlay/detail/ProtocolMessage.h
  src/xrpld/overlay/detail/ProtocolVersion.cpp
Labels: Ready to merge, Bug, Trivial

#5173 Add logging and improve counting of amendment votes from UNL
  src/xrpld/app/consensus/RCLConsensus.cpp
  src/xrpld/app/misc/AmendmentTable.h
  src/xrpld/app/misc/detail/AmendmentTable.cpp
Labels: Ready to merge

#5312 Replace `assert` with `XRPL_ASSERT`
  src/xrpld/app/misc/detail/AmendmentTable.cpp
  src/xrpld/overlay/detail/PeerImp.cpp
  src/xrpld/overlay/detail/PeerImp.h
Labels: Ready to merge, Trivial

#5318 Acquire previously failed transaction set from
  src/xrpld/app/ledger/detail/TransactionAcquire.cpp
Labels: Ready to merge

#5302 Detailed consensus data correlated together.
  include/xrpl/basics/Log.h
  include/xrpl/beast/utility/Journal.h
  include/xrpl/beast/utility/WrappedSink.h
  src/libxrpl/basics/Log.cpp
  src/libxrpl/beast/utility/src/beast_Journal.cpp
  src/test/beast/beast_Journal_test.cpp
  src/test/csf/Peer.h
  src/test/csf/Sim.h
  src/test/jtx/CaptureLogs.h
  src/test/jtx/CheckMessageLogs.h
  src/test/server/ServerStatus_test.cpp
  src/test/server/Server_test.cpp
  src/test/unit_test/SuiteJournal.h
  src/xrpld/app/consensus/RCLConsensus.cpp
  src/xrpld/app/consensus/RCLConsensus.h
  src/xrpld/app/main/Application.cpp
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/app/misc/NetworkOPs.h
  src/xrpld/consensus/Consensus.cpp
  src/xrpld/consensus/Consensus.h
Labels: Ready to merge

#5325 chore: Move "assert" and "werr" flags from "actions/build"
  .github/actions/build/action.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: Ready to merge, Trivial

#5326 Introduced new XRPLF UNL subdomain as an intermediate step for migration
  cfg/validators-example.txt
Labels: Trivial
