Repository XRPLF/rippled, pull requests merged in 2025-07, with the labels that each got.

#5529 fix: crash when trace-logging in tests
  src/test/unit_test/SuiteJournal.h
Labels: Ready to merge, Trivial

#5487 Decouple CredentialHelpers from xrpld/app/tx
  src/xrpld/app/misc/CredentialHelpers.cpp
  src/xrpld/app/misc/CredentialHelpers.h
  src/xrpld/app/tx/detail/DeleteAccount.cpp
  src/xrpld/app/tx/detail/Escrow.cpp
  src/xrpld/app/tx/detail/PayChan.cpp
  src/xrpld/app/tx/detail/Payment.cpp
Labels: Ready to merge

#5544 Remove circular `jtx.h` includes
  src/test/app/Vault_test.cpp
  src/test/jtx.h
  src/test/jtx/impl/mpt.cpp
  src/test/jtx/impl/permissioned_dex.cpp
  src/test/jtx/impl/permissioned_domains.cpp
  src/test/jtx/mpt.h
  src/test/jtx/permissioned_dex.h
  src/test/jtx/permissioned_domains.h
Labels: Ready to merge, Trivial

#5543 Fix compilation error with clang-20, cleanup
  cmake/RippledSettings.cmake
  include/xrpl/basics/Expected.h
  include/xrpl/beast/hash/hash_append.h
  src/test/basics/Buffer_test.cpp
Labels: Ready to merge, Trivial

#5548 Downgrade required CMake version for Antithesis SDK
  external/antithesis-sdk/CMakeLists.txt
Labels: Trivial

#5526 chore: Removed unused headers
  include/xrpl/basics/Buffer.h
  include/xrpl/basics/StringUtilities.h
  include/xrpl/basics/algorithm.h
  include/xrpl/basics/hardened_hash.h
  include/xrpl/basics/mulDiv.h
  include/xrpl/basics/tagged_integer.h
  include/xrpl/beast/clock/abstract_clock.h
  include/xrpl/beast/clock/manual_clock.h
  include/xrpl/beast/container/aged_container_utility.h
  include/xrpl/beast/container/detail/aged_associative_container.h
  include/xrpl/beast/container/detail/aged_ordered_container.h
  include/xrpl/beast/core/LexicalCast.h
  include/xrpl/beast/hash/hash_append.h
  include/xrpl/beast/net/IPAddress.h
  include/xrpl/beast/net/IPAddressV4.h
  include/xrpl/beast/net/IPAddressV6.h
  include/xrpl/beast/net/IPEndpoint.h
  include/xrpl/beast/rfc2616.h
  include/xrpl/beast/test/yield_to.h
  include/xrpl/beast/unit_test/reporter.h
  include/xrpl/beast/unit_test/runner.h
  include/xrpl/json/json_value.h
  include/xrpl/protocol/AccountID.h
  include/xrpl/protocol/ApiVersion.h
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/FeeUnits.h
  include/xrpl/protocol/Indexes.h
  include/xrpl/protocol/Issue.h
  include/xrpl/protocol/MultiApiJson.h
  include/xrpl/protocol/Permissions.h
  include/xrpl/protocol/PublicKey.h
  include/xrpl/protocol/SOTemplate.h
  include/xrpl/protocol/STBase.h
  include/xrpl/protocol/STBlob.h
  include/xrpl/protocol/STValidation.h
  include/xrpl/protocol/Serializer.h
  include/xrpl/protocol/Sign.h
  include/xrpl/protocol/XChainAttestations.h
  include/xrpl/protocol/detail/b58_utils.h
  include/xrpl/protocol/digest.h
  include/xrpl/protocol/json_get_or_throw.h
  include/xrpl/resource/Charge.h
  include/xrpl/resource/Gossip.h
  include/xrpl/server/detail/BaseHTTPPeer.h
  include/xrpl/server/detail/Door.h
  include/xrpl/server/detail/io_list.h
  src/xrpld/app/misc/HashRouter.h
  src/xrpld/core/JobQueue.h
  src/xrpld/ledger/PaymentSandbox.h
  src/xrpld/shamap/SHAMap.h
Labels: Trivial

#5554 Add gcc-12 workaround
  include/xrpl/beast/utility/rngfill.h
Labels: Ready to merge, Trivial

#4934 remove the type filter from "ledger" RPC command
  include/xrpl/protocol/ErrorCodes.h
  src/test/rpc/LedgerRPC_test.cpp
  src/xrpld/app/ledger/LedgerToJson.h
  src/xrpld/app/ledger/detail/LedgerToJson.cpp
  src/xrpld/rpc/handlers/LedgerHandler.cpp
  src/xrpld/rpc/handlers/LedgerHandler.h
Labels: Ready to merge

#5585 Fix macos runner
  .github/workflows/macos.yml
Labels: Ready to merge

#5576 Revert to std::shared_mutex from boost::shared_mutex
  src/xrpld/app/misc/ValidatorList.h
  src/xrpld/overlay/detail/PeerImp.h
Labels: Ready to merge, Trivial

#5587 Remove include(default) from libxrpl profile
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
  conan/profiles/libxrpl
Labels: Trivial

#5563 Restructure beast::rngfill
  include/xrpl/beast/utility/rngfill.h
Labels: Ready to merge

#5598 Trying to fix clang-format
  .github/workflows/clang-format.yml
Labels: Ready to merge, Trivial

#5509 Add support for `DomainID` in `MPTokenIssuance` transactions
  include/xrpl/protocol/detail/ledger_entries.macro
  include/xrpl/protocol/detail/transactions.macro
  src/test/app/MPToken_test.cpp
  src/test/jtx/impl/mpt.cpp
  src/test/jtx/mpt.h
  src/xrpld/app/tx/detail/MPTokenIssuanceCreate.cpp
  src/xrpld/app/tx/detail/MPTokenIssuanceSet.cpp
Labels: Ready to merge

#5607 Switch instrumentation workflow to use dependencies
  .github/workflows/nix.yml
Labels: Ready to merge, Trivial

#5264 Updates Conan dependencies: Boost
  BUILD.md
  conan/profiles/default
  conanfile.py
  external/soci/conanfile.py
  include/xrpl/basics/Log.h
  src/libxrpl/basics/FileUtilities.cpp
  src/test/jtx/TrustedPublisherServer.h
  src/test/server/ServerStatus_test.cpp
  src/test/unit_test/FileDirGuard.h
  src/xrpld/app/main/Application.cpp
  src/xrpld/app/main/Main.cpp
Labels: Ready to merge

#5635 Fix crash in `Slot::deletePeer`
  src/xrpld/overlay/Slot.h
  src/xrpld/overlay/detail/OverlayImpl.cpp
Labels: Ready to merge, Bug

#5639 Revert "ci: Build all conan dependencies from source for now (#5623)"
  .github/actions/dependencies/action.yml
Labels: Trivial
