Repository XRPLF/rippled, pull requests merged in 2025-09, with the labels that each got.

#5756 Add required `disable_ccache` option
  .github/workflows/build-test.yml
Labels: Ready to merge, Trivial

#5751 chore: Use conan lockfile
  .pre-commit-config.yaml
  BUILD.md
  conan.lock
Labels: Ready to merge

#5763 ci: Use cleanup-workspace action
  .github/workflows/build-test.yml
Labels: Ready to merge, Trivial

#5761 fix: Add missing info to notify-clio workflow
  .github/workflows/notify-clio.yml
Labels: Ready to merge, Trivial

#5753 chore: Use tooling provided by pre-commit
  .github/workflows/check-format.yml
  .pre-commit-config.yaml
Labels: Ready to merge

#5752 chore: remove redundant word in comment
  src/xrpld/app/paths/Pathfinder.h
Labels: Ready to merge, Documentation, Trivial

#5750 Enable fixAMMClawbackRounding
  include/xrpl/protocol/detail/features.macro
Labels: Ready to merge, Trivial

#5776 chore: "passed" job fails if any previous jobs failed
  .github/workflows/on-pr.yml
Labels: Ready to merge, CI, Trivial

#5781 ci: Run only 10 instances of upload-conan-deps using max-parallel
  .github/scripts/strategy-matrix/generate.py
  .github/workflows/reusable-strategy-matrix.yml
  .github/workflows/reusable-upload-conan-deps-os.yml
  .github/workflows/upload-conan-deps.yml
Labels: Ready to merge

#5784 ci: Use default conan install format
  .github/actions/build-deps/action.yml
Labels: Ready to merge, Trivial

#5783 ci: Add missing dependencies to workflows
  .github/workflows/on-pr.yml
  .github/workflows/on-trigger.yml
  .github/workflows/upload-conan-deps.yml
Labels: Ready to merge, Trivial

#5650 fix PermissionDelegation: fixDelegateV1_1
  include/xrpl/protocol/Permissions.h
  include/xrpl/protocol/TxFormats.h
  include/xrpl/protocol/detail/features.macro
  include/xrpl/protocol/detail/transactions.macro
  include/xrpl/protocol/jss.h
  src/libxrpl/protocol/Permissions.cpp
  src/libxrpl/protocol/TxFormats.cpp
  src/test/app/AMMClawback_test.cpp
  src/test/app/Delegate_test.cpp
  src/xrpld/app/tx/detail/DelegateSet.cpp
  src/xrpld/app/tx/detail/Payment.cpp
  src/xrpld/app/tx/detail/applySteps.cpp
Labels: Ready to merge, Amendment

#5792 Remove LoanDraw transaction
  include/xrpl/protocol/detail/ledger_entries.macro
  include/xrpl/protocol/detail/transactions.macro
  src/test/app/Batch_test.cpp
  src/test/app/EscrowToken_test.cpp
  src/test/app/Loan_test.cpp
  src/test/jtx/TestHelpers.h
  src/test/jtx/impl/TestHelpers.cpp
  src/xrpld/app/tx/detail/LoanDelete.cpp
  src/xrpld/app/tx/detail/LoanDraw.cpp
  src/xrpld/app/tx/detail/LoanDraw.h
  src/xrpld/app/tx/detail/LoanManage.cpp
  src/xrpld/app/tx/detail/LoanPay.cpp
  src/xrpld/app/tx/detail/LoanSet.cpp
Labels: Ready to merge

#5669 Bugfix: Adds graceful peer disconnection
  src/xrpld/overlay/detail/ConnectAttempt.cpp
  src/xrpld/overlay/detail/ConnectAttempt.h
  src/xrpld/overlay/detail/PeerImp.cpp
  src/xrpld/overlay/detail/PeerImp.h
Labels: Ready to merge

#5797 Rename mutable flags for DynamicMPT XLS-94d
  include/xrpl/protocol/LedgerFormats.h
  include/xrpl/protocol/TxFlags.h
  src/test/app/MPToken_test.cpp
  src/test/jtx/impl/mpt.cpp
  src/xrpld/app/tx/detail/MPTokenIssuanceCreate.cpp
  src/xrpld/app/tx/detail/MPTokenIssuanceSet.cpp
Labels: Ready to merge

#5646 fix(amendment): add missing fields for keylets to ledger objects
  include/xrpl/protocol/Indexes.h
  include/xrpl/protocol/detail/features.macro
  include/xrpl/protocol/detail/ledger_entries.macro
  src/test/app/Escrow_test.cpp
  src/test/app/MultiSign_test.cpp
  src/test/app/Oracle_test.cpp
  src/test/app/PayChan_test.cpp
  src/test/jtx/impl/Oracle.cpp
  src/xrpld/app/tx/detail/Escrow.cpp
  src/xrpld/app/tx/detail/PayChan.cpp
  src/xrpld/app/tx/detail/SetOracle.cpp
  src/xrpld/app/tx/detail/SetSignerList.cpp
Labels: Ready to merge, Amendment

#5799 chore: Limit CI build and test parallelism to reduce resource contention
  .github/workflows/build-test.yml
Labels: Trivial

#5801 chore: Build and test all configs for daily scheduled run
  .github/workflows/on-trigger.yml
Labels: Trivial

#5726 test: add STInteger and STParsedJSON tests
  include/xrpl/protocol/Permissions.h
  include/xrpl/protocol/STParsedJSON.h
  src/libxrpl/protocol/Permissions.cpp
  src/libxrpl/protocol/STInteger.cpp
  src/libxrpl/protocol/STParsedJSON.cpp
  src/test/protocol/STInteger_test.cpp
  src/test/protocol/STParsedJSON_test.cpp
Labels: Ready to merge

#5767 Fix http header case sensitivity issue
  .github/scripts/levelization/results/ordering.txt
  src/libxrpl/net/HTTPClient.cpp
  src/tests/libxrpl/CMakeLists.txt
  src/tests/libxrpl/net/HTTPClient.cpp
  src/tests/libxrpl/net/main.cpp
Labels: Ready to merge

#5746 test: add more comprehensive tests for `FeeVote`
  src/test/app/FeeVote_test.cpp
Labels: Ready to merge

#5818 ci: Call all reusable workflows reusable
  .github/scripts/levelization/README.md
  .github/workflows/on-pr.yml
  .github/workflows/on-trigger.yml
  .github/workflows/reusable-build-test.yml
  .github/workflows/reusable-check-levelization.yml
  .github/workflows/reusable-check-missing-commits.yml
  .github/workflows/reusable-notify-clio.yml
Labels: Ready to merge, Trivial

#5819 switch `fixIncludeKeyletFields` to `Supported::yes`
  include/xrpl/protocol/detail/features.macro
Labels: Ready to merge, Trivial

#5594 Pre-lending protocol refactoring 4: Transactor extra signing support
  src/xrpld/app/tx/detail/Transactor.cpp
  src/xrpld/app/tx/detail/Transactor.h
Labels: Ready to merge
