Repository XRPLF/rippled, pull requests merged in 2025-08, with the labels that each got.

#5478 Update BUILD for conan2
  BUILD.md
  docs/build/environment.md
Labels: Ready to merge

#5654 Upload Conan dependencies upon merge into develop
  .github/actions/dependencies/action.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: Trivial

#5486 Moving mutex to partition level
  include/xrpl/basics/SHAMapHash.h
  include/xrpl/basics/TaggedCache.h
  include/xrpl/basics/TaggedCache.ipp
  include/xrpl/basics/partitioned_unordered_map.h
  include/xrpl/protocol/Protocol.h
  src/test/basics/TaggedCache_test.cpp
  src/xrpld/app/ledger/LedgerHistory.cpp
  src/xrpld/rpc/handlers/GetCounts.cpp
Labels: Ready to merge

#5469 Optimize hash performance by avoiding allocating hash state object
  include/xrpl/beast/hash/xxhasher.h
  src/test/beast/xxhasher_test.cpp
Labels: Ready to merge, Perf Attn Needed

#5662 Set CONAN_REMOTE_URL also for forks
  .github/workflows/libxrpl.yml
  .github/workflows/macos.yml
  .github/workflows/nix.yml
  .github/workflows/windows.yml
Labels: Ready to merge, Trivial

#5664 Improves how the reason to refuse a peer connection is logged
  src/xrpld/overlay/detail/ConnectAttempt.cpp
  src/xrpld/overlay/detail/OverlayImpl.cpp
  src/xrpld/peerfinder/PeerfinderManager.h
Labels: Ready to merge, Bug, Trivial

#5477 Decouple net from xrpld and move rpc related classes to the rpc folder
  Builds/levelization/results/loops.txt
  Builds/levelization/results/ordering.txt
  cmake/RippledCore.cmake
  cmake/RippledInstall.cmake
  include/xrpl/net/AutoSocket.h
  include/xrpl/net/HTTPClient.h
  include/xrpl/net/HTTPClientSSLContext.h
  include/xrpl/net/RegisterSSLCerts.h
  src/libxrpl/net/HTTPClient.cpp
  src/libxrpl/net/RegisterSSLCerts.cpp
  src/libxrpl/net/images/interrupt_sequence.png
  src/libxrpl/net/images/states.png
  src/test/jtx/impl/Env.cpp
  src/test/jtx/impl/utility.cpp
  src/test/rpc/RPCCall_test.cpp
  src/xrpld/app/ledger/BookListeners.h
  src/xrpld/app/main/GRPCServer.h
  src/xrpld/app/main/Main.cpp
  src/xrpld/app/misc/NetworkOPs.h
  src/xrpld/app/misc/detail/WorkSSL.cpp
  src/xrpld/app/misc/detail/WorkSSL.h
  src/xrpld/app/paths/PathRequest.h
  src/xrpld/core/detail/Config.cpp
  src/xrpld/rpc/Context.h
  src/xrpld/rpc/InfoSub.h
  src/xrpld/rpc/RPCCall.h
  src/xrpld/rpc/RPCSub.h
  src/xrpld/rpc/detail/InfoSub.cpp
  src/xrpld/rpc/detail/RPCCall.cpp
  src/xrpld/rpc/detail/RPCHandler.cpp
  src/xrpld/rpc/detail/RPCSub.cpp
  src/xrpld/rpc/detail/WSInfoSub.h
  src/xrpld/rpc/handlers/Subscribe.cpp
Labels: Ready to merge

#5617 Update Conan dependencies: OpenSSL
  cmake/RippledCompiler.cmake
  conanfile.py
Labels: Perf Attn Needed

#5718 chore: Fix file formatting
  .github/actions/build-deps/action.yml
  .github/actions/build-test/action.yml
  .github/scripts/levelization/README.md
  .github/workflows/build-test.yml
  .github/workflows/check-missing-commits.yml
  .github/workflows/notify-clio.yml
  .github/workflows/on-pr.yml
  .github/workflows/on-trigger.yml
  .github/workflows/publish-docs.yml
  bin/git/setup-upstreams.sh
  bin/git/squash-branches.sh
  cfg/rippled-example.cfg
  cmake/RippledCore.cmake
  docs/0001-negative-unl/negativeUNLSqDiagram.puml
  docs/0010-ledger-replay/ledger_replay_classes.puml
  docs/0010-ledger-replay/ledger_replay_sequence.puml
  include/xrpl/protocol/Batch.h
  include/xrpl/protocol/TxFlags.h
  include/xrpl/protocol/detail/ledger_entries.macro
  src/libxrpl/protocol/Permissions.cpp
  src/test/app/Delegate_test.cpp
  src/test/app/NFTokenAuth_test.cpp
  src/test/csf/collectors.h
  src/test/jtx/delegate.h
  src/test/jtx/impl/delegate.cpp
  src/xrpld/app/tx/detail/DelegateSet.cpp
  src/xrpld/app/tx/detail/DelegateSet.h
Labels: Trivial

#5739 chore: Run test jobs if files changed or "Ready to merge"
  .github/workflows/on-pr.yml
Labels: Ready to merge, CI

#5690 adds additional logging to differentiate why connections were refused
  src/test/overlay/tx_reduce_relay_test.cpp
  src/test/peerfinder/PeerFinder_test.cpp
  src/xrpld/overlay/detail/OverlayImpl.cpp
  src/xrpld/peerfinder/PeerfinderManager.h
  src/xrpld/peerfinder/detail/Counts.h
  src/xrpld/peerfinder/detail/Logic.h
  src/xrpld/peerfinder/detail/PeerfinderConfig.cpp
  src/xrpld/peerfinder/detail/PeerfinderManager.cpp
Labels: Ready to merge
