Repository XRPLF/rippled, pull requests merged in 2025-01, with the labels that each got.

#5202 refactor: add `rpcName` to `LEDGER_ENTRY` macro
  include/xrpl/protocol/LedgerFormats.h
  include/xrpl/protocol/detail/ledger_entries.macro
  include/xrpl/protocol/jss.h
  src/libxrpl/protocol/LedgerFormats.cpp
  src/xrpld/rpc/detail/RPCHelpers.cpp
Labels: Passed

#5233 added macos dependency installation
  .github/workflows/macos.yml
Labels: Passed

#5048 XLS-46: DynamicNFT
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/TxFlags.h
  include/xrpl/protocol/detail/features.macro
  include/xrpl/protocol/detail/transactions.macro
  include/xrpl/protocol/nft.h
  src/test/app/NFToken_test.cpp
  src/test/jtx/impl/token.cpp
  src/test/jtx/token.h
  src/xrpld/app/tx/detail/NFTokenMint.cpp
  src/xrpld/app/tx/detail/NFTokenModify.cpp
  src/xrpld/app/tx/detail/NFTokenModify.h
  src/xrpld/app/tx/detail/NFTokenUtils.cpp
  src/xrpld/app/tx/detail/NFTokenUtils.h
  src/xrpld/app/tx/detail/applySteps.cpp
Labels: Passed

#5235 fix failing assert in `connect` RPC
  src/test/rpc/Connect_test.cpp
  src/xrpld/rpc/handlers/Connect.cpp
Labels: Passed

#5246 Fix the flag processing of NFTokenModify
  include/xrpl/protocol/TxFlags.h
  src/test/app/NFToken_test.cpp
  src/xrpld/app/tx/detail/NFTokenModify.cpp
Labels: Ready to merge (Author)

#5194 Fix levelization script to ignore commented includes
  Builds/levelization/levelization.sh
Labels: Ready to merge (Author)

#5228 fix: Use the same compiler options for xrpl.libxrpl and all its submodules
  .github/actions/build/action.yml
  .github/workflows/nix.yml
  cmake/RippledCore.cmake
  cmake/RippledInterface.cmake
  cmake/RippledSettings.cmake
  src/xrpld/app/paths/detail/DirectStep.cpp
Labels: Ready to merge (Author), CI, Build System, Bug, Perf impact not expected

#5252 fix: Errors consistency in LedgerEntry::parsePermissionedDomains()
  src/test/rpc/LedgerRPC_test.cpp
  src/xrpld/rpc/handlers/LedgerEntry.cpp
Labels: Ready to merge (Author)

#5215 TRIVIAL: Update release instructions
  .github/workflows/missing-commits.yml
  CONTRIBUTING.md
  bin/git/setup-upstreams.sh
  bin/git/squash-branches.sh
  bin/git/update-version.sh
Labels: Ready to merge, Reviewed, Trivial

#5242 Unit tests to recreate invalid index logic error
  src/test/app/Regression_test.cpp
  src/xrpld/ledger/detail/CachedView.cpp
Labels: Ready to merge, Bug, Tech Debt, Perf impact not expected

#5207 Cleanup API-CHANGELOG.md
  API-CHANGELOG.md
Labels: Ready to merge, Documentation, Trivial

#5251 Add a space to the applied log
  src/xrpld/app/tx/detail/Transactor.cpp
Labels: Ready to merge, Low Priority, Trivial

#5245 [trivial] Use XRPL_ASSERT in `PermissionedDomainDelete`
  src/xrpld/app/tx/detail/PermissionedDomainDelete.cpp
Labels: Ready to merge, Trivial

#5112 Implement threshold for the intersection of lists of validators
  API-CHANGELOG.md
  cfg/validators-example.txt
  include/xrpl/protocol/jss.h
  src/test/app/ValidatorList_test.cpp
  src/test/core/Config_test.cpp
  src/xrpld/app/main/Application.cpp
  src/xrpld/app/misc/ValidatorList.h
  src/xrpld/app/misc/detail/ValidatorList.cpp
  src/xrpld/core/Config.h
  src/xrpld/core/ConfigSections.h
  src/xrpld/core/detail/Config.cpp
Labels: Ready to merge

#5240 chore: Update Visual Studio CI to VS 2022, and add VS Debug builds
  .github/workflows/windows.yml
Labels: Ready to merge, CI, Trivial, Perf impact not expected

#5196 Fix CI unit tests
  .github/workflows/macos.yml
  include/xrpl/basics/BasicConfig.h
  include/xrpl/server/detail/ServerImpl.h
  src/libxrpl/basics/BasicConfig.cpp
  src/libxrpl/server/Port.cpp
  src/test/app/LedgerReplay_test.cpp
  src/test/app/XChain_test.cpp
  src/test/core/Config_test.cpp
  src/test/jtx/Env.h
  src/test/jtx/envconfig.h
  src/test/jtx/impl/Env.cpp
  src/test/jtx/impl/JSONRPCClient.cpp
  src/test/jtx/impl/WSClient.cpp
  src/test/jtx/impl/envconfig.cpp
  src/test/ledger/View_test.cpp
  src/test/rpc/AccountObjects_test.cpp
  src/test/rpc/LedgerRPC_test.cpp
  src/test/rpc/LedgerRequestRPC_test.cpp
  src/test/rpc/ServerInfo_test.cpp
  src/test/rpc/Subscribe_test.cpp
  src/test/rpc/ValidatorInfo_test.cpp
  src/test/rpc/ValidatorRPC_test.cpp
  src/test/server/Server_test.cpp
  src/test/unit_test/multi_runner.cpp
  src/xrpld/app/main/Application.cpp
  src/xrpld/app/main/GRPCServer.cpp
  src/xrpld/app/main/GRPCServer.h
  src/xrpld/core/detail/Config.cpp
  src/xrpld/overlay/detail/OverlayImpl.cpp
  src/xrpld/rpc/ServerHandler.h
  src/xrpld/rpc/detail/ServerHandler.cpp
Labels: Ready to merge

#5069 Add RPC "simulate" to execute a dry run of a transaction
  API-CHANGELOG.md
  include/xrpl/protocol/ErrorCodes.h
  include/xrpl/protocol/jss.h
  src/libxrpl/protocol/ErrorCodes.cpp
  src/libxrpl/protocol/InnerObjectFormats.cpp
  src/test/app/NFToken_test.cpp
  src/test/app/PseudoTx_test.cpp
  src/test/app/Regression_test.cpp
  src/test/app/TxQ_test.cpp
  src/test/consensus/NegativeUNL_test.cpp
  src/test/rpc/JSONRPC_test.cpp
  src/test/rpc/Simulate_test.cpp
  src/xrpld/app/ledger/detail/BuildLedger.cpp
  src/xrpld/app/ledger/detail/LedgerMaster.cpp
  src/xrpld/app/ledger/detail/OpenLedger.cpp
  src/xrpld/app/main/Main.cpp
  src/xrpld/app/misc/NetworkOPs.cpp
  src/xrpld/app/misc/TxQ.h
  src/xrpld/app/misc/detail/TxQ.cpp
  src/xrpld/app/tx/apply.h
  src/xrpld/app/tx/applySteps.h
  src/xrpld/app/tx/detail/ApplyContext.cpp
  src/xrpld/app/tx/detail/ApplyContext.h
  src/xrpld/app/tx/detail/Transactor.cpp
  src/xrpld/app/tx/detail/Transactor.h
  src/xrpld/app/tx/detail/apply.cpp
  src/xrpld/app/tx/detail/applySteps.cpp
  src/xrpld/ledger/ApplyView.h
  src/xrpld/ledger/ApplyViewImpl.h
  src/xrpld/ledger/detail/ApplyStateTable.cpp
  src/xrpld/ledger/detail/ApplyStateTable.h
  src/xrpld/ledger/detail/ApplyViewImpl.cpp
  src/xrpld/net/detail/RPCCall.cpp
  src/xrpld/rpc/detail/Handler.cpp
  src/xrpld/rpc/detail/TransactionSign.cpp
  src/xrpld/rpc/detail/TransactionSign.h
  src/xrpld/rpc/handlers/Handlers.h
  src/xrpld/rpc/handlers/Simulate.cpp
  src/xrpld/rpc/handlers/Submit.cpp
Labels: Ready to merge

#5260 Reverse merge hotfix release 2.3.1
  .github/workflows/nix.yml
  Builds/levelization/results/ordering.txt
  RELEASENOTES.md
  include/xrpl/resource/Charge.h
  include/xrpl/resource/Consumer.h
  include/xrpl/resource/Fees.h
  include/xrpl/resource/detail/Logic.h
  include/xrpl/resource/detail/Tuning.h
  src/libxrpl/resource/Charge.cpp
  src/libxrpl/resource/Consumer.cpp
  src/libxrpl/resource/Fees.cpp
  src/test/app/LedgerReplay_test.cpp
  src/test/overlay/reduce_relay_test.cpp
  src/test/overlay/tx_reduce_relay_test.cpp
  src/xrpld/app/ledger/detail/InboundLedger.cpp
  src/xrpld/app/ledger/detail/InboundTransactions.cpp
  src/xrpld/app/ledger/detail/LedgerMaster.cpp
  src/xrpld/overlay/Overlay.h
  src/xrpld/overlay/Peer.h
  src/xrpld/overlay/detail/OverlayImpl.cpp
  src/xrpld/overlay/detail/OverlayImpl.h
  src/xrpld/overlay/detail/PeerImp.cpp
  src/xrpld/overlay/detail/PeerImp.h
  src/xrpld/rpc/detail/RPCHelpers.cpp
  src/xrpld/rpc/detail/ServerHandler.cpp
  src/xrpld/rpc/handlers/GatewayBalances.cpp
  src/xrpld/rpc/handlers/LedgerHandler.cpp
  src/xrpld/rpc/handlers/PathFind.cpp
  src/xrpld/rpc/handlers/RipplePathFind.cpp
  src/xrpld/rpc/handlers/SignFor.cpp
  src/xrpld/rpc/handlers/SignHandler.cpp
  src/xrpld/rpc/handlers/SubmitMultiSigned.cpp
Labels: CI, Build System, Bug, Trivial

#5187 Add deep freeze feature (XLS-77d)
  include/xrpl/protocol/Feature.h
  include/xrpl/protocol/LedgerFormats.h
  include/xrpl/protocol/TxFlags.h
  include/xrpl/protocol/detail/features.macro
  include/xrpl/protocol/jss.h
  src/test/app/Freeze_test.cpp
  src/test/ledger/Invariants_test.cpp
  src/test/rpc/AccountLines_test.cpp
  src/xrpld/app/paths/TrustLine.h
  src/xrpld/app/paths/detail/StepChecks.h
  src/xrpld/app/tx/detail/CashCheck.cpp
  src/xrpld/app/tx/detail/CreateOffer.cpp
  src/xrpld/app/tx/detail/InvariantCheck.cpp
  src/xrpld/app/tx/detail/InvariantCheck.h
  src/xrpld/app/tx/detail/NFTokenAcceptOffer.cpp
  src/xrpld/app/tx/detail/NFTokenAcceptOffer.h
  src/xrpld/app/tx/detail/OfferStream.cpp
  src/xrpld/app/tx/detail/SetTrust.cpp
  src/xrpld/ledger/View.h
  src/xrpld/ledger/detail/View.cpp
  src/xrpld/rpc/handlers/AccountLines.cpp
Labels: Ready to merge, Amendment
